"""Add 22 new DDD/AI kinds to kinds_meta.json (KIND_GAP_AUDIT M1 output)."""
import json, sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
META = ROOT / ".cex" / "kinds_meta.json"

NEW_KINDS = {
    "domain_event": {"pillar":"P12","llm_function":"CALL","naming":"p12_dev_{{name}}.md","max_bytes":3072,"core":False,"description":"Immutable record of something significant that happened in the domain, distinct from system-level signals","boundary":"Domain-level event. NOT signal (system-level) nor audit_log (compliance record). DDD Domain Event.","status":"stable","upstream_source":"Evans DDD 2003","spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
    "data_contract": {"pillar":"P06","llm_function":"CONSTRAIN","naming":"p06_dc_{{name}}.md","max_bytes":4096,"core":False,"description":"Schema-level agreement between a data producer and consumer defining structure, semantics, and SLA","boundary":"Producer-consumer schema contract. NOT dataset_card (data metadata) nor validation_schema (output validation). DDD Published Language.","status":"stable","upstream_source":None,"spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
    "domain_vocabulary": {"pillar":"P01","llm_function":"INJECT","naming":"p01_dv_{{domain}}.md","max_bytes":5120,"core":True,"description":"Governed registry of canonical terms for a bounded context, enforcing Ubiquitous Language across agents","boundary":"Controlled vocabulary for one domain. NOT glossary_entry (single term) nor ontology (formal relations). DDD Ubiquitous Language registry.","status":"stable","upstream_source":"Evans DDD 2003","spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
    "alert_rule": {"pillar":"P09","llm_function":"GOVERN","naming":"p09_alr_{{name}}.md","max_bytes":2048,"core":False,"description":"Observable threshold condition that triggers a notification or automated response","boundary":"Monitoring trigger. NOT guardrail (LLM behavior constraint) nor quality_gate (artifact scoring). Industry: Prometheus alerting rule.","status":"stable","upstream_source":None,"spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
    "bounded_context": {"pillar":"P08","llm_function":"CONSTRAIN","naming":"p08_bc_{{name}}.md","max_bytes":4096,"core":False,"description":"Explicit boundary within which a domain model applies, with its own vocabulary and rules","boundary":"DDD boundary definition. NOT component_map (deployment structure) nor namespace (code boundary). Evans Bounded Context.","status":"stable","upstream_source":"Evans DDD 2003","spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
    "deployment_manifest": {"pillar":"P09","llm_function":"COLLABORATE","naming":"p09_dm_{{name}}.md","max_bytes":4096,"core":False,"description":"Specification of what artifacts to deploy, where to deploy them, and how to configure the deployment","boundary":"Release deployment spec. NOT env_config (runtime environment) nor sandbox_spec (test environment). Industry: Kubernetes manifest, Helm values.","status":"stable","upstream_source":None,"spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
    "slo_definition": {"pillar":"P09","llm_function":"GOVERN","naming":"p09_slo_{{name}}.md","max_bytes":3072,"core":False,"description":"Measurable service level objective with target threshold and error budget for a system or agent","boundary":"Measurable SLO target. NOT enterprise_sla (contractual SLA) nor quality_gate (build-time artifact scoring).","status":"stable","upstream_source":None,"spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
    "lineage_record": {"pillar":"P01","llm_function":"INJECT","naming":"p01_lin_{{name}}.md","max_bytes":3072,"core":False,"description":"Provenance chain documenting how a knowledge artifact was derived, transformed, and curated","boundary":"Knowledge provenance. NOT audit_log (compliance event log) nor citation (source reference). Maps to PROV-O standard.","status":"stable","upstream_source":None,"spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
    "saga": {"pillar":"P12","llm_function":"COLLABORATE","naming":"p12_sag_{{name}}.md","max_bytes":4096,"core":False,"description":"Long-running distributed transaction composed of local steps with compensating actions for rollback","boundary":"Distributed transaction with compensation. NOT workflow (sequential steps) nor process_manager (event coordination). Saga pattern (Garcia-Molina 1987).","status":"stable","upstream_source":None,"spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
    "canary_config": {"pillar":"P09","llm_function":"GOVERN","naming":"p09_can_{{name}}.md","max_bytes":2048,"core":False,"description":"Gradual traffic rollout configuration for safe deployment with automatic rollback triggers","boundary":"Canary deployment spec. NOT feature_flag (boolean toggle) nor ab_test_config (experiment split). Industry: Argo Rollouts, Flagger.","status":"stable","upstream_source":None,"spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
    "aggregate_root": {"pillar":"P06","llm_function":"CONSTRAIN","naming":"p06_agr_{{name}}.md","max_bytes":4096,"core":False,"description":"DDD entry point entity that enforces domain invariants and controls access to its aggregate cluster","boundary":"DDD aggregate root. NOT interface (contract definition) nor input_schema (data validation). Evans Aggregate Root.","status":"stable","upstream_source":"Evans DDD 2003","spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
    "value_object": {"pillar":"P06","llm_function":"CONSTRAIN","naming":"p06_vo_{{name}}.md","max_bytes":2048,"core":False,"description":"Immutable typed value without identity, defined entirely by its attributes and equality","boundary":"Immutable value type. NOT type_def (generic type) nor enum_def (enumeration). Evans Value Object.","status":"stable","upstream_source":"Evans DDD 2003","spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
    "process_manager": {"pillar":"P12","llm_function":"CALL","naming":"p12_pm_{{name}}.md","max_bytes":4096,"core":False,"description":"Event-driven coordinator for multi-step processes that routes domain events and issues commands to participants","boundary":"Event-driven process coordinator. NOT workflow (step-sequential) nor supervisor (agent hierarchy). Enterprise Integration Patterns: Process Manager.","status":"stable","upstream_source":None,"spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
    "event_stream": {"pillar":"P04","llm_function":"CALL","naming":"p04_evs_{{name}}.md","max_bytes":3072,"core":False,"description":"Configuration for a real-time ordered sequence of domain events consumed by one or more subscribers","boundary":"Real-time event stream config. NOT webhook (single outbound call) nor signal (internal nucleus signal). Industry: Kafka topic, Kinesis stream.","status":"stable","upstream_source":None,"spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
    "constitutional_rule": {"pillar":"P11","llm_function":"CONSTRAIN","naming":"p11_cr_{{name}}.md","max_bytes":2048,"core":True,"description":"Absolute behavioral constraint for an agent that cannot be overridden by instructions, context, or operator configuration","boundary":"Absolute constraint. NOT guardrail (soft constraint with fallback) nor safety_policy (policy document). Anthropic Constitutional AI.","status":"stable","upstream_source":"Anthropic Constitutional AI 2022","spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
    "preference_dataset": {"pillar":"P11","llm_function":"GOVERN","naming":"p11_pd_{{name}}.md","max_bytes":4096,"core":False,"description":"Curated dataset of human-labeled preference pairs used for RLHF training or direct preference optimization","boundary":"RLHF preference data. NOT eval_dataset (evaluation examples) nor golden_test (expected outputs). Industry: RLHF reward modeling.","status":"stable","upstream_source":None,"spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
    "drift_detector": {"pillar":"P11","llm_function":"GOVERN","naming":"p11_dd_{{name}}.md","max_bytes":3072,"core":False,"description":"Monitor that detects distribution shift in model inputs, outputs, or behavioral patterns over time","boundary":"Distribution shift monitor. NOT regression_check (code regression) nor benchmark (point-in-time score). Industry: Evidently AI, Arize.","status":"stable","upstream_source":None,"spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
    "working_memory": {"pillar":"P10","llm_function":"INJECT","naming":"p10_wm_{{task}}.md","max_bytes":3072,"core":False,"description":"Short-term context store for a single active task, cleared after task completion","boundary":"Task-scoped short-term memory. NOT session_state (session persistence) nor entity_memory (long-term entity store). Cognitive: working memory.","status":"stable","upstream_source":None,"spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
    "episodic_memory": {"pillar":"P10","llm_function":"INJECT","naming":"p10_ep_{{name}}.md","max_bytes":4096,"core":False,"description":"Long-term store of past interactions indexed by episode for retrieval and context injection","boundary":"Episode-indexed long-term memory. NOT entity_memory (entity facts) nor memory_summary (compressed context). Cognitive: Tulving 1972.","status":"stable","upstream_source":"Tulving 1972","spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
    "prospective_memory": {"pillar":"P10","llm_function":"COLLABORATE","naming":"p10_pro_{{name}}.md","max_bytes":2048,"core":False,"description":"Scheduled future actions and reminders that an agent must execute at a future time or trigger condition","boundary":"Future-action memory. NOT schedule (workflow schedule config) nor session_state (current session). Cognitive: prospective memory.","status":"stable","upstream_source":None,"spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
    "circuit_breaker": {"pillar":"P09","llm_function":"GOVERN","naming":"p09_cb_{{name}}.md","max_bytes":3072,"core":False,"description":"Resilience pattern that auto-disables failing dependencies and allows recovery after a cooldown period","boundary":"Dependency circuit breaker. NOT fallback_chain (ordered provider fallback) nor rate_limit_config (inbound throttle). Industry: Hystrix, Resilience4j.","status":"stable","upstream_source":None,"spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
    "backpressure_policy": {"pillar":"P09","llm_function":"GOVERN","naming":"p09_bp_{{name}}.md","max_bytes":2048,"core":False,"description":"Policy defining how a system responds when downstream consumers cannot keep up with upstream producers","boundary":"Downstream overwhelm handling. NOT rate_limit_config (inbound throttle) nor circuit_breaker (dependency failure). Reactive Streams backpressure.","status":"stable","upstream_source":None,"spec_version":None,"last_reviewed":"2026-04-17","deprecated_by":None},
}

with open(META) as f:
    meta = json.load(f)

added = []
for kind, entry in NEW_KINDS.items():
    if kind not in meta:
        meta[kind] = entry
        added.append(kind)
    else:
        print(f"SKIP (exists): {kind}")

with open(META, "w") as f:
    json.dump(meta, f, indent=2, ensure_ascii=False, sort_keys=True)

print(f"Added {len(added)} kinds. Total: {len(meta)}")
for k in sorted(added):
    print(f"  + {k} ({NEW_KINDS[k]['pillar']})")
