#!/usr/bin/env python3
"""
CEX Boot Generator — reads nucleus_models.yaml → generates boot/*.cmd

Usage:
  python _tools/cex_boot_gen.py              # generate all boot scripts
  python _tools/cex_boot_gen.py --dry-run    # show what would be generated
  python _tools/cex_boot_gen.py --nucleus n03  # generate one
  python _tools/cex_boot_gen.py --show       # show current config table

Reads:  .cex/config/nucleus_models.yaml
Writes: boot/n0{1-6}.cmd + boot/cex.cmd + fallback scripts
"""
import yaml, sys, os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / ".cex" / "config" / "nucleus_models.yaml"
TEMPLATE = ROOT / ".cex" / "config" / "nucleus_models.template.yaml"
BOOT_DIR = ROOT / "boot"

# Nucleus metadata (domain prompts)
NUCLEUS_META = {
    "n07": {
        "title": "CEX-N07-ORCHESTRATOR",
        "var": "CEX_NUCLEUS=N07",
        "prompt": "Voce e N07 Orchestrator do CEX. Orquestra nucleos, nunca constroi. Leia CLAUDE.md e .claude/rules/n07-orchestrator.md.",
    },
    "n01": {
        "title": "CEX-N01-RESEARCH",
        "var": "CEX_NUCLEUS=N01",
        "prompt": "Voce e N01 Research Nucleus do CEX. Dominio: research, analise, papers, competidores. SE EXISTIR .cex/runtime/handoffs/n01_task.md LEIA E EXECUTE IMEDIATAMENTE.",
    },
    "n02": {
        "title": "CEX-N02-MARKETING",
        "var": "CEX_NUCLEUS=N02",
        "prompt": "Voce e N02 Marketing Nucleus do CEX. Dominio: copy, ads, campanhas, brand voice. SE EXISTIR .cex/runtime/handoffs/n02_task.md LEIA E EXECUTE IMEDIATAMENTE.",
    },
    "n03": {
        "title": "CEX-N03-BUILDER",
        "var": "CEX_NUCLEUS=N03",
        "prompt": "Voce e o Builder Nucleus N03 do CEX. 8F pipeline obrigatorio. Leia .claude/rules/n03-8f-enforcement.md e N03_engineering/agents/agent_engineering.md. SE EXISTIR .cex/runtime/handoffs/n03_task.md LEIA E EXECUTE IMEDIATAMENTE.",
    },
    "n04": {
        "title": "CEX-N04-KNOWLEDGE",
        "var": "CEX_NUCLEUS=N04",
        "prompt": "Voce e N04 Knowledge Nucleus do CEX. Dominio: RAG, indexacao, knowledge cards, taxonomia. SE EXISTIR .cex/runtime/handoffs/n04_task.md LEIA E EXECUTE IMEDIATAMENTE.",
    },
    "n05": {
        "title": "CEX-N05-OPERATIONS",
        "var": "CEX_NUCLEUS=N05",
        "prompt": "Voce e N05 Operations Nucleus do CEX. Dominio: code review, testing, CI/CD, deploy. SE EXISTIR .cex/runtime/handoffs/n05_task.md LEIA E EXECUTE IMEDIATAMENTE.",
    },
    "n06": {
        "title": "CEX-N06-COMMERCIAL",
        "var": "CEX_NUCLEUS=N06",
        "prompt": "Voce e N06 Commercial Nucleus do CEX. Dominio: pricing, funnels, monetizacao, brand. SE EXISTIR .cex/runtime/handoffs/n06_task.md LEIA E EXECUTE IMEDIATAMENTE.",
    },
}

# CLI-specific boot templates
def build_claude_cmd(nucleus: str, cfg: dict, meta: dict) -> str:
    model = cfg.get("model", "claude-sonnet-4-6")
    flags = cfg.get("flags", "--dangerously-skip-permissions --permission-mode bypassPermissions --no-chrome")
    mcps = cfg.get("mcps", "")
    settings = cfg.get("settings", "")

    lines = [
        "@echo off",
        f":: CEX {nucleus.upper()} — {meta['title']}",
        f":: Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml",
        f":: CLI: claude | Model: {model}",
        "",
        f"title {meta['title']}",
        "set CLAUDECODE=",
        f"set {meta['var']}",
        f"set CEX_ROOT={ROOT}",
        'cd /d "%CEX_ROOT%"',
        "",
        f"set MODEL=--model {model}",
        f"set FLAGS={flags}",
    ]
    if mcps:
        lines.append(f'set MCP=--mcp-config %CEX_ROOT%\\{mcps.replace("/", chr(92))}')
    else:
        lines.append("set MCP=")
    if settings:
        lines.append(f'set SETTINGS=--settings %CEX_ROOT%\\{settings.replace("/", chr(92))}')
    else:
        lines.append("set SETTINGS=")

    lines += [
        "",
        ":: ALWAYS interactive — task comes from handoff file, never CLI args",
        f'claude %FLAGS% %MODEL% %MCP% %SETTINGS% "{meta["prompt"]}"',
    ]
    return "\n".join(lines) + "\n"


def build_gemini_cmd(nucleus: str, cfg: dict, meta: dict) -> str:
    model = cfg.get("model", "gemini-2.5-pro")
    flags = cfg.get("flags", "--yolo")

    return "\n".join([
        "@echo off",
        f":: CEX {nucleus.upper()} — {meta['title']}",
        f":: Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml",
        f":: CLI: gemini | Model: {model}",
        "",
        f"title {meta['title']}",
        f"set {meta['var']}",
        f"set CEX_ROOT={ROOT}",
        'cd /d "%CEX_ROOT%"',
        "",
        ":: Force subscription OAuth (clear API keys)",
        "set GOOGLE_API_KEY=",
        "set GEMINI_API_KEY=",
        "set GOOGLE_AI_API_KEY=",
        "",
        ":: ALWAYS interactive — task comes from handoff file, never CLI args",
        f'gemini -m {model} {flags} "{meta["prompt"]}"',
    ]) + "\n"


def build_codex_cmd(nucleus: str, cfg: dict, meta: dict) -> str:
    model = cfg.get("model", "o3")
    flags = cfg.get("flags", "--full-auto")

    return "\n".join([
        "@echo off",
        f":: CEX {nucleus.upper()} — {meta['title']}",
        f":: Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml",
        f":: CLI: codex | Model: {model}",
        "",
        f"title {meta['title']}",
        f"set {meta['var']}",
        f"set CEX_ROOT={ROOT}",
        'cd /d "%CEX_ROOT%"',
        "",
        ":: ALWAYS interactive — task comes from handoff file, never CLI args",
        f'codex -m {model} {flags} "{meta["prompt"]}"',
    ]) + "\n"


def build_pi_cmd(nucleus: str, cfg: dict, meta: dict) -> str:
    model = cfg.get("model", "anthropic/claude-opus-4-6")
    thinking = cfg.get("thinking", "xhigh")

    return "\n".join([
        "@echo off",
        f":: CEX {nucleus.upper()} — {meta['title']}",
        f":: Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml",
        f":: CLI: pi | Model: {model} | Thinking: {thinking}",
        "",
        f"title {meta['title']}",
        f"set {meta['var']}",
        f"set CEX_ROOT={ROOT}",
        'cd /d "%CEX_ROOT%"',
        "",
        f"pi --model {model} --thinking {thinking}",
    ]) + "\n"


def build_ollama_cmd(nucleus: str, cfg: dict, meta: dict) -> str:
    model = cfg.get("model", "qwen3:32b")
    flags = cfg.get("flags", "")

    return "\n".join([
        "@echo off",
        f":: CEX {nucleus.upper()} — {meta['title']}",
        f":: Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml",
        f":: CLI: ollama | Model: {model}",
        "",
        f"title {meta['title']}",
        f"set {meta['var']}",
        f"set CEX_ROOT={ROOT}",
        'cd /d "%CEX_ROOT%"',
        "",
        ":: Local model — no API keys needed",
        f'ollama run {model}',
    ]) + "\n"


BUILDERS = {
    "claude": build_claude_cmd,
    "gemini": build_gemini_cmd,
    "codex": build_codex_cmd,
    "pi": build_pi_cmd,
    "ollama": build_ollama_cmd,
}


def load_config() -> dict:
    if CONFIG.exists():
        with open(CONFIG, "r", encoding="utf-8") as f:
            return yaml.safe_load(f) or {}
    elif TEMPLATE.exists():
        print(f"[WARN] No {CONFIG.name} found. Using template.")
        with open(TEMPLATE, "r", encoding="utf-8") as f:
            return yaml.safe_load(f) or {}
    else:
        print("[ERROR] No nucleus_models.yaml or template found.")
        sys.exit(1)


def generate(config: dict, only: str = None, dry_run: bool = False):
    BOOT_DIR.mkdir(exist_ok=True)
    generated = []

    for nucleus, cfg in config.items():
        if only and nucleus != only:
            continue
        if nucleus not in NUCLEUS_META:
            print(f"[SKIP] Unknown nucleus: {nucleus}")
            continue

        meta = NUCLEUS_META[nucleus]
        cli = cfg.get("cli", "claude")
        builder = BUILDERS.get(cli)

        if not builder:
            print(f"[ERROR] Unknown CLI '{cli}' for {nucleus}")
            continue

        # Main boot script
        content = builder(nucleus, cfg, meta)
        if nucleus == "n07":
            path = BOOT_DIR / "cex.cmd"
        else:
            path = BOOT_DIR / f"{nucleus}.cmd"

        if dry_run:
            print(f"\n{'='*60}")
            print(f"  Would write: {path}")
            print(f"  CLI: {cli} | Model: {cfg.get('model','?')}")
            print(f"{'='*60}")
            print(content)
        else:
            path.write_text(content, encoding="utf-8")
            generated.append((path.name, cli, cfg.get('model','?')))

        # Fallback script (if defined)
        fb = cfg.get("fallback")
        if fb:
            fb_cli = fb.get("cli", "claude")
            fb_builder = BUILDERS.get(fb_cli)
            if fb_builder:
                fb_content = fb_builder(nucleus, fb, meta)
                fb_path = BOOT_DIR / f"{nucleus}-{fb_cli}.cmd"
                if dry_run:
                    print(f"\n  [FALLBACK] Would write: {fb_path}")
                    print(f"  CLI: {fb_cli} | Model: {fb.get('model','?')}")
                else:
                    fb_path.write_text(fb_content, encoding="utf-8")
                    generated.append((fb_path.name, f"fallback:{fb_cli}", fb.get('model','?')))

    if not dry_run and generated:
        print(f"[BOOT-GEN] Generated {len(generated)} scripts:")
        for name, cli, model in generated:
            print(f"  OK boot/{name} ({cli} {model})")


def show_table(config: dict):
    print(f"\n{'Nucleus':<10} {'CLI':<10} {'Model':<35} {'Fallback':<20}")
    print("-" * 80)
    for nucleus in ["n07", "n01", "n02", "n03", "n04", "n05", "n06"]:
        cfg = config.get(nucleus, {})
        cli = cfg.get("cli", "?")
        model = cfg.get("model", "?")
        fb = cfg.get("fallback", {})
        fb_str = f"{fb.get('cli','')}/{fb.get('model','')}" if fb else "-"
        print(f"{nucleus.upper():<10} {cli:<10} {model:<35} {fb_str:<20}")
    print()


if __name__ == "__main__":
    args = sys.argv[1:]
    config = load_config()

    if "--help" in args:
        print(__doc__)
    elif "--show" in args:
        show_table(config)
    elif "--dry-run" in args:
        nucleus = args[args.index("--nucleus") + 1] if "--nucleus" in args else None
        generate(config, only=nucleus, dry_run=True)
    else:
        nucleus = args[args.index("--nucleus") + 1] if "--nucleus" in args else None
        generate(config, only=nucleus)
