#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""CEX QLoRA Fine-Tuning Trainer -- Per-nucleus adapter training.

Trains QLoRA adapters on a base model using per-nucleus JSONL datasets
generated by cex_ft_dataset.py. Produces Ollama-compatible adapter files.

Requirements:
    pip install unsloth transformers datasets peft trl

Usage:
    python _tools/cex_ft_train.py --nucleus N03 --base gemma3:27b
    python _tools/cex_ft_train.py --nucleus N03 --base qwen3:14b --epochs 3
    python _tools/cex_ft_train.py --all --base gemma3:27b
    python _tools/cex_ft_train.py --nucleus N03 --dry-run  # show config only

Output:
    _data/ft/adapters/cex-n03-qlora/  (LoRA adapter files)
    _data/ft/adapters/cex-n03.Modelfile  (Ollama Modelfile)
"""

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
FT_DIR = ROOT / "_data" / "ft"
ADAPTERS_DIR = FT_DIR / "adapters"

# Base model mappings: friendly name -> HuggingFace model ID
BASE_MODELS = {
    # Primary: Gemma 4 MoE (26B total, 4B active -- fits 16GB VRAM)
    "gemma4:26b": "google/gemma-4-26b-a4b",
    # Fallbacks
    "gemma3:27b": "google/gemma-3-27b-it",
    "gemma3:12b": "google/gemma-3-12b-it",
    "qwen3:14b": "Qwen/Qwen3-14B",
    "qwen3:8b": "Qwen/Qwen3-8B",
}

# Default QLoRA hyperparameters per nucleus
NUCLEUS_CONFIGS = {
    "N01": {
        "r": 16, "lora_alpha": 32, "epochs": 3, "lr": 2e-4,
        "max_seq_length": 4096, "notes": "Research: longer outputs, fewer pairs"
    },
    "N02": {
        "r": 16, "lora_alpha": 32, "epochs": 5, "lr": 2e-4,
        "max_seq_length": 2048, "notes": "Marketing: creative, needs more epochs"
    },
    "N03": {
        "r": 32, "lora_alpha": 64, "epochs": 3, "lr": 1e-4,
        "max_seq_length": 4096, "notes": "Builder: largest dataset, higher rank"
    },
    "N04": {
        "r": 16, "lora_alpha": 32, "epochs": 3, "lr": 2e-4,
        "max_seq_length": 4096, "notes": "Knowledge: structured outputs"
    },
    "N05": {
        "r": 32, "lora_alpha": 64, "epochs": 3, "lr": 1e-4,
        "max_seq_length": 4096, "notes": "Operations: largest dataset, higher rank"
    },
    "N06": {
        "r": 16, "lora_alpha": 32, "epochs": 5, "lr": 2e-4,
        "max_seq_length": 2048, "notes": "Commercial: small dataset, more epochs"
    },
    "N07": {
        "r": 16, "lora_alpha": 32, "epochs": 3, "lr": 2e-4,
        "max_seq_length": 2048, "notes": "Orchestration: dispatch patterns"
    },
}

# Ollama Modelfile template
MODELFILE_TEMPLATE = """FROM {base_model}
ADAPTER ./{adapter_dir}/
PARAMETER temperature 0.3
PARAMETER num_ctx 65536
PARAMETER top_p 0.9
SYSTEM \"\"\"You are {nucleus_name}, the {nucleus_role} nucleus of CEX.
You follow the 8F pipeline (CONSTRAIN, BECOME, INJECT, REASON, CALL, PRODUCE, GOVERN, COLLABORATE).
You produce structured artifacts with YAML frontmatter and markdown body.
Quality target: 9.0+. Density target: 0.85+.
You NEVER self-score quality (quality: null always).\"\"\"
"""

NUCLEUS_ROLES = {
    "N01": ("N01 Intelligence", "research and analysis"),
    "N02": ("N02 Marketing", "marketing and creative"),
    "N03": ("N03 Builder", "artifact construction"),
    "N04": ("N04 Knowledge", "knowledge management"),
    "N05": ("N05 Operations", "code, testing, and deployment"),
    "N06": ("N06 Commercial", "commercial and monetization"),
    "N07": ("N07 Orchestrator", "dispatch and orchestration"),
}


def count_pairs(jsonl_path: Path) -> int:
    """Count lines in JSONL file."""
    if not jsonl_path.exists():
        return 0
    with open(jsonl_path, "r", encoding="utf-8") as f:
        return sum(1 for _ in f)


def show_config(nucleus: str, base_model: str, config: dict[str, Any]) -> int:
    """Display training configuration."""
    nuc_lower = nucleus.lower()
    jsonl_path = FT_DIR / f"ft_{nuc_lower}.jsonl"
    pairs = count_pairs(jsonl_path)
    name, role = NUCLEUS_ROLES.get(nucleus, (nucleus, "unknown"))

    print(f"\n{'='*60}")
    print(f"QLoRA Training Config: {name}")
    print(f"{'='*60}")
    print(f"Base model:     {base_model} -> {BASE_MODELS.get(base_model, base_model)}")
    print(f"Dataset:        {jsonl_path}")
    print(f"Training pairs: {pairs}")
    print(f"LoRA rank (r):  {config['r']}")
    print(f"LoRA alpha:     {config['lora_alpha']}")
    print(f"Epochs:         {config['epochs']}")
    print(f"Learning rate:  {config['lr']}")
    print(f"Max seq length: {config['max_seq_length']}")
    print(f"Notes:          {config['notes']}")
    print(f"Output:         {ADAPTERS_DIR / f'cex-{nuc_lower}-qlora'}")
    print(f"Modelfile:      {ADAPTERS_DIR / f'cex-{nuc_lower}.Modelfile'}")

    # Estimate training time (rough: ~0.5s per pair per epoch on RTX 5070 Ti)
    est_seconds = pairs * config["epochs"] * 0.5
    est_minutes = est_seconds / 60
    print(f"Est. time:      ~{est_minutes:.0f} min ({est_seconds:.0f}s)")
    print(f"Est. VRAM:      ~14GB (Q4 base + LoRA gradients)")
    return pairs


def generate_modelfile(nucleus: str, base_model: str) -> Path:
    """Generate Ollama Modelfile for the fine-tuned model."""
    nuc_lower = nucleus.lower()
    name, role = NUCLEUS_ROLES.get(nucleus, (nucleus, "unknown"))
    adapter_dir = f"cex-{nuc_lower}-qlora"

    content = MODELFILE_TEMPLATE.format(
        base_model=base_model,
        adapter_dir=adapter_dir,
        nucleus_name=name,
        nucleus_role=role,
    )

    ADAPTERS_DIR.mkdir(parents=True, exist_ok=True)
    modelfile_path = ADAPTERS_DIR / f"cex-{nuc_lower}.Modelfile"
    modelfile_path.write_text(content, encoding="utf-8")
    return modelfile_path


def train_nucleus(nucleus: str, base_model: str, config: dict[str, Any]) -> bool:
    """Train QLoRA adapter for a single nucleus."""
    nuc_lower = nucleus.lower()
    jsonl_path = FT_DIR / f"ft_{nuc_lower}.jsonl"

    if not jsonl_path.exists():
        print(f"[FAIL] Dataset not found: {jsonl_path}")
        return False

    pairs = count_pairs(jsonl_path)
    if pairs < 10:
        print(f"[WARN] Only {pairs} pairs for {nucleus} -- skipping (need >= 10)")
        return False

    hf_model = BASE_MODELS.get(base_model, base_model)
    output_dir = ADAPTERS_DIR / f"cex-{nuc_lower}-qlora"

    print(f"\n[INFO] Training {nucleus} adapter...")
    print(f"[INFO] Base: {hf_model}, Pairs: {pairs}, Epochs: {config['epochs']}")

    try:
        # Import training libraries
        from unsloth import FastLanguageModel
        from datasets import load_dataset
        from trl import SFTTrainer
        from transformers import TrainingArguments
        import torch

        # Load base model with 4-bit quantization
        model, tokenizer = FastLanguageModel.from_pretrained(
            model_name=hf_model,
            max_seq_length=config["max_seq_length"],
            dtype=None,  # auto-detect
            load_in_4bit=True,
        )

        # Add LoRA adapters
        model = FastLanguageModel.get_peft_model(
            model,
            r=config["r"],
            lora_alpha=config["lora_alpha"],
            target_modules=[
                "q_proj", "k_proj", "v_proj", "o_proj",
                "gate_proj", "up_proj", "down_proj",
            ],
            lora_dropout=0.05,
            bias="none",
            use_gradient_checkpointing="unsloth",
        )

        # Load dataset
        dataset = load_dataset("json", data_files=str(jsonl_path), split="train")

        # Format as Alpaca
        def format_alpaca(example: dict[str, Any]) -> dict[str, str]:
            text = (
                f"### Instruction:\n{example['instruction']}\n\n"
                f"### Input:\n{example['input']}\n\n"
                f"### Response:\n{example['output']}"
            )
            return {"text": text}

        dataset = dataset.map(format_alpaca)

        # Training args
        output_dir.mkdir(parents=True, exist_ok=True)
        training_args = TrainingArguments(
            output_dir=str(output_dir),
            per_device_train_batch_size=1,
            gradient_accumulation_steps=4,
            num_train_epochs=config["epochs"],
            learning_rate=config["lr"],
            fp16=not torch.cuda.is_bf16_supported(),
            bf16=torch.cuda.is_bf16_supported(),
            logging_steps=10,
            save_strategy="epoch",
            warmup_ratio=0.05,
            weight_decay=0.01,
            lr_scheduler_type="cosine",
            report_to="none",
        )

        # Train
        trainer = SFTTrainer(
            model=model,
            tokenizer=tokenizer,
            train_dataset=dataset,
            dataset_text_field="text",
            max_seq_length=config["max_seq_length"],
            args=training_args,
        )

        trainer.train()

        # Save adapter
        model.save_pretrained(str(output_dir))
        tokenizer.save_pretrained(str(output_dir))

        # Generate Modelfile
        mf_path = generate_modelfile(nucleus, base_model)

        print(f"[OK] Adapter saved: {output_dir}")
        print(f"[OK] Modelfile: {mf_path}")
        print(f"[OK] Deploy: ollama create cex-{nuc_lower} -f {mf_path}")
        return True

    except ImportError as e:
        print(f"[FAIL] Missing dependency: {e}")
        print(f"[INFO] Install: pip install unsloth transformers datasets peft trl")
        return False
    except Exception as e:
        print(f"[FAIL] Training error: {e}")
        return False


def main() -> None:
    parser = argparse.ArgumentParser(description="CEX QLoRA Fine-Tuning Trainer")
    parser.add_argument("--nucleus", default=None,
                        help="Target nucleus (e.g. N03)")
    parser.add_argument("--all", action="store_true",
                        help="Train all nuclei sequentially")
    parser.add_argument("--base", default="gemma4:26b",
                        help="Base model (default: gemma4:26b)")
    parser.add_argument("--epochs", type=int, default=None,
                        help="Override epochs count")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show config only, don't train")
    parser.add_argument("--modelfile-only", action="store_true",
                        help="Generate Ollama Modelfiles only")
    args = parser.parse_args()

    nuclei = []
    if args.all:
        nuclei = ["N01", "N02", "N03", "N04", "N05", "N06", "N07"]
    elif args.nucleus:
        nuclei = [args.nucleus.upper()]
    else:
        print("[FAIL] Specify --nucleus N03 or --all")
        sys.exit(1)

    for nuc in nuclei:
        config = NUCLEUS_CONFIGS.get(nuc, NUCLEUS_CONFIGS["N03"]).copy()
        if args.epochs:
            config["epochs"] = args.epochs

        if args.dry_run:
            show_config(nuc, args.base, config)
            continue

        if args.modelfile_only:
            mf = generate_modelfile(nuc, args.base)
            print(f"[OK] {mf}")
            continue

        show_config(nuc, args.base, config)
        train_nucleus(nuc, args.base, config)

    if args.dry_run:
        print(f"\n[INFO] Dry run complete. Use without --dry-run to train.")
        total_pairs = sum(
            count_pairs(FT_DIR / f"ft_{n.lower()}.jsonl") for n in nuclei
        )
        print(f"[INFO] Total training pairs: {total_pairs}")


if __name__ == "__main__":
    main()
