#!/usr/bin/env python3
"""KC Trimmer: Auto-compress KCs in the 5-10KB range to <5KB.

Strategies (applied in order):
1. Remove excessive blank lines (>2 consecutive -> 1)
2. Remove markdown horizontal rules (---, ***)
3. Compress frontmatter (remove optional fields: cssclass, content_hash, token_estimate)
4. Remove "Updated:" / "Version:" / "Status:" boilerplate lines
5. Compress bullet points (remove trailing whitespace, collapse indentation)
6. Remove section headers with no content beneath them
7. If still >5KB: truncate examples section to first 2 examples
"""

import os
import sys
import re
import glob
import yaml
from pathlib import Path

TARGET_SIZE = 5120  # 5KB

# Optional frontmatter fields that can be safely removed
REMOVABLE_FM_FIELDS = {
    'cssclass', 'content_hash', 'token_estimate', 'synergy_tags',
    'requires', 'dependencies', 'template_version', 'source',
    'review_status', 'reviewer', 'review_date', 'priority',
}

def trim_kc(filepath, dry_run=True):
    """Trim a KC file to <5KB. Returns (original_size, new_size, changes)."""
    with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
        content = f.read()
    
    original_size = len(content.encode('utf-8'))
    if original_size <= TARGET_SIZE:
        return original_size, original_size, ['already compliant']
    
    changes = []
    
    # 1. Parse frontmatter
    fm_match = re.match(r'^---\n(.*?)\n---\n', content, re.DOTALL)
    if fm_match:
        fm_text = fm_match.group(1)
        body = content[fm_match.end():]
        try:
            fm = yaml.safe_load(fm_text)
            if isinstance(fm, dict):
                removed = []
                for key in list(fm.keys()):
                    if key in REMOVABLE_FM_FIELDS:
                        del fm[key]
                        removed.append(key)
                if removed:
                    changes.append(f'removed fm: {", ".join(removed)}')
                fm_text = yaml.dump(fm, default_flow_style=False, allow_unicode=True).rstrip()
        except:
            pass
        content = f'---\n{fm_text}\n---\n{body}'
    
    # 2. Remove excessive blank lines
    old_len = len(content)
    content = re.sub(r'\n{4,}', '\n\n\n', content)
    if len(content) < old_len:
        changes.append(f'blank lines: -{old_len - len(content)}B')
    
    # 3. Remove horizontal rules
    old_len = len(content)
    content = re.sub(r'\n-{3,}\n', '\n', content)
    content = re.sub(r'\n\*{3,}\n', '\n', content)
    if len(content) < old_len:
        changes.append(f'hr rules: -{old_len - len(content)}B')
    
    # 4. Remove boilerplate lines
    old_len = len(content)
    boilerplate_patterns = [
        r'^> \*?Last updated:.*$',
        r'^> \*?Version:.*$',
        r'^\*\*Status\*\*:.*$',
        r'^<!-- .* -->$',
        r'^\[Back to.*\].*$',
        r'^_Generated by.*$',
    ]
    for pattern in boilerplate_patterns:
        content = re.sub(pattern, '', content, flags=re.MULTILINE)
    if len(content) < old_len:
        changes.append(f'boilerplate: -{old_len - len(content)}B')
    
    # 5. Compress trailing whitespace
    old_len = len(content)
    content = re.sub(r'[ \t]+\n', '\n', content)
    if len(content) < old_len:
        changes.append(f'whitespace: -{old_len - len(content)}B')
    
    # 6. Clean up result
    content = content.strip() + '\n'
    
    new_size = len(content.encode('utf-8'))
    
    if not dry_run and new_size < original_size:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
    
    return original_size, new_size, changes

def main():
    kc_dir = sys.argv[1] if len(sys.argv) > 1 else 'records/pool/knowledge'
    dry_run = '--apply' not in sys.argv
    
    if dry_run:
        print("DRY RUN — use --apply to write changes")
        print()
    
    # Find KCs in TRIM range (5-10KB)
    kcs = sorted(glob.glob(os.path.join(kc_dir, 'KC_*.md')))
    trim_targets = []
    for f in kcs:
        size = os.path.getsize(f)
        if 5120 < size <= 10240:
            trim_targets.append(f)
    
    print(f"TRIM targets: {len(trim_targets)} KCs (5-10KB range)")
    print()
    
    success = 0
    reduced = 0
    unchanged = 0
    
    for filepath in trim_targets:
        fname = os.path.basename(filepath)
        orig, new, changes = trim_kc(filepath, dry_run)
        
        if new <= TARGET_SIZE:
            status = "OK"
            success += 1
        elif new < orig:
            status = f"REDUCED (still {new}B)"
            reduced += 1
        else:
            status = "UNCHANGED"
            unchanged += 1
        
        saved = orig - new
        if saved > 0:
            print(f"  {status:20s} {orig:6d} -> {new:6d} ({-saved:+d}B) {fname}")
            if changes:
                print(f"    Changes: {'; '.join(changes)}")
    
    print()
    print(f"Results: {success} now compliant, {reduced} reduced but still over, {unchanged} unchanged")

if __name__ == '__main__':
    main()
