@echo off
:: CEX N07 -- CEX-N07-ORCHESTRATOR
:: Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml
:: CLI: claude | Model: claude-opus-4-6

title CEX-N07-ORCHESTRATOR
set CEX_NUCLEUS=N07
set CEX_ROOT=%~dp0..
cd /d "%CEX_ROOT%"

claude --dangerously-skip-permissions --permission-mode bypassPermissions --no-chrome --name "CEX-N07" --model claude-opus-4-6 --append-system-prompt ".cex/config/context_self_select.md"
