# CEX N07 -- CEX-N07-ORCHESTRATOR
# Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml + nucleus_sins.yaml
# CLI: claude | Model: claude-opus-4-6 | Context: 1000000
# Sin: Orchestrating Sloth (Orchestrating Sloth)

# --- UX: Window appearance ---
$Host.UI.RawUI.WindowTitle = "CEX-N07-ORCHESTRATOR [claude-opus-4-6]"
try {
    $Host.UI.RawUI.BackgroundColor = "Black"
    $Host.UI.RawUI.ForegroundColor = "White"
    $bufSize = $Host.UI.RawUI.BufferSize
    $bufSize.Width = 160; $bufSize.Height = 9999
    $Host.UI.RawUI.BufferSize = $bufSize
    $winSize = $Host.UI.RawUI.WindowSize
    $winSize.Width = [Math]::Min(160, $Host.UI.RawUI.MaxWindowSize.Width)
    $winSize.Height = [Math]::Min(40, $Host.UI.RawUI.MaxWindowSize.Height)
    $Host.UI.RawUI.WindowSize = $winSize
    Clear-Host
} catch {}

Write-Host ""
Write-Host "  [*] N07 Orchestrating Sloth - Orchestrating Sloth" -ForegroundColor DarkCyan
Write-Host "  ==================================================" -ForegroundColor DarkGray
Write-Host "  Too lazy to do it myself. Dispatching." -ForegroundColor DarkGray
Write-Host "  claude-opus-4-6  |  1000K context  |  8F pipeline" -ForegroundColor DarkGray
Write-Host ""

# --- Environment ---
$env:CLAUDECODE = ""
$env:CEX_NUCLEUS = "N07"
$env:CEX_ROOT = "C:\Users\PC\Documents\GitHub\cex"
Set-Location $env:CEX_ROOT

# --- Launch CLI ---
# System prompt (sin identity + domain role) injected via --append-system-prompt
$sysPrompt = @'
You are driven by Orchestrating Sloth -- orchestrating sloth. You NEVER build directly. You dispatch, monitor, and consolidate. Your laziness makes you delegate perfectly -- right nucleus, right task. Your sloth makes you the most efficient orchestrator in the system. --- You are N07 Orchestrator of CEX. Dispatch nuclei, never build. Read CLAUDE.md e .claude/rules/n07-orchestrator.md.
'@

# Initial message (what the nucleus does on startup)
$initialMsg = @'
Ready. What do you need?
'@

# Build argument list (avoids PowerShell parsing -- flags as operators)
$args = @("--dangerously-skip-permissions", "--permission-mode", "bypassPermissions", "--no-chrome", "--model", "claude-opus-4-6")
$args += "--append-system-prompt", "N07_admin/agent_card_n07.md"
$args += "--append-system-prompt", ".cex/config/context_self_select.md"
$args += "--append-system-prompt", $sysPrompt
# no MCP config
# no settings
$args += $initialMsg

# Call operator & ensures external command execution
& claude @args
