# CEX N07 -- CEX-N07-ORCHESTRATOR
# Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml + nucleus_sins.yaml
# CLI: claude | Model: claude-opus-4-6 | Context: 1000000
# Sin: Orchestrating Sloth (Orchestrating Sloth)

# --- UX: Window title with mission + sin + status ---
# Auto-detect root from script location (worktree-agnostic)
$cexRoot = Split-Path -Parent $PSScriptRoot
$nucleus = "n07"
$sinName = "Orchestrating Sloth"
$modelShort = "claude-opus-4-6" -replace "claude-", ""

# Detect mission from handoff file
$mission = ""
$handoff = "$cexRoot\.cex\runtime\handoffs\${nucleus}_task.md"
if (Test-Path $handoff) {
    $content = Get-Content $handoff -Head 10 -EA SilentlyContinue
    foreach ($line in $content) {
        if ($line -match "^mission:\s*(.+)$") {
            $mission = $Matches[1].Trim()
            break
        }
    }
}

# Detect git repo name + branch
$gitBranch = ""
$gitRepo = ""
try {
    $gitBranch = (git rev-parse --abbrev-ref HEAD 2>$null)
    $gitRemote = (git remote get-url origin 2>$null)
    if ($gitRemote -match "[/:]([^/]+?)(?:\.git)?$") { $gitRepo = $Matches[1] }
} catch {}

# Build title: N0X Sin | repo@branch [mission] -- STATUS
function Set-CexTitle($status) {
    $t = "N07 $sinName"
    if ($gitRepo) { $t += " | $gitRepo" }
    if ($gitBranch) { $t += "@$gitBranch" }
    if ($mission) { $t += " [$mission]" }
    $t += " -- $status"
    $Host.UI.RawUI.WindowTitle = $t
}

Set-CexTitle "BOOTING"

try {
    $Host.UI.RawUI.BackgroundColor = "Black"
    $Host.UI.RawUI.ForegroundColor = "White"
    if (-not $env:CEX_GRID) {
        # Solo mode: set buffer + window size. Grid mode: spawn_grid controls sizing.
        $bufSize = $Host.UI.RawUI.BufferSize
        $bufSize.Width = 160; $bufSize.Height = 9999
        $Host.UI.RawUI.BufferSize = $bufSize
        $winSize = $Host.UI.RawUI.WindowSize
        $winSize.Width = [Math]::Min(160, $Host.UI.RawUI.MaxWindowSize.Width)
        $winSize.Height = [Math]::Min(40, $Host.UI.RawUI.MaxWindowSize.Height)
        $Host.UI.RawUI.WindowSize = $winSize
    }
    Clear-Host
} catch {}

# --- Operational state probe (all best-effort, never blocks boot) ---
function Probe-State {
    $s = [ordered]@{
        ContextPct   = $null
        Running      = @()
        Handoffs     = @()
        LastCommit   = ""
        GitMod       = 0
        GitUntr      = 0
        LastMission  = ""
        LastMissionAgo = ""
    }

    # Context estimate: ~29k project tokens + ~340k Claude Code core = ~37%
    # Recomputed from disk each boot so it tracks reality if rules grow/shrink.
    try {
        $rules = (Get-ChildItem "$cexRoot\.claude\rules\*.md" -EA SilentlyContinue | Measure-Object Length -Sum).Sum
        $clmd  = (Get-Item "$cexRoot\CLAUDE.md" -EA SilentlyContinue).Length
        $agents = (Get-ChildItem "$cexRoot\.claude\agents\*.md" -EA SilentlyContinue).Count
        $agentBytes = $agents * 200  # ~200 bytes per description in Agent tool enum
        $projectTok = [int](($rules + $clmd + $agentBytes + 8000) / 4)  # +8k for append-system-prompt files, skills list, MEMORY.md
        $coreTok    = 340000  # Claude Code 2.1 core (fixed empirical baseline)
        $totalTok   = $projectTok + $coreTok
        $s.ContextPct = [Math]::Round(($totalTok / 1000000.0) * 100, 1)
    } catch {}

    # Running nuclei (read PID file, extract nucleus column, dedupe + liveness check)
    try {
        $pidFile = "$cexRoot\.cex\runtime\pids\spawn_pids.txt"
        if (Test-Path $pidFile) {
            $lines = Get-Content $pidFile -EA SilentlyContinue | Where-Object { $_.Trim() -ne "" }
            $live = @()
            foreach ($ln in $lines) {
                $parts = $ln -split '\s+'
                if ($parts.Count -ge 2) {
                    $wpid = $parts[0]
                    $nuc  = $parts[1]
                    # Skip stale: only count if wrapper PID is still alive
                    $alive = $false
                    try { if (Get-Process -Id $wpid -EA SilentlyContinue) { $alive = $true } } catch {}
                    if ($alive) { $live += $nuc }
                }
            }
            $s.Running = $live | Select-Object -Unique | Sort-Object
        }
    } catch {}

    # Pending handoffs (n0X_task.md in runtime/handoffs/)
    try {
        $hoDir = "$cexRoot\.cex\runtime\handoffs"
        if (Test-Path $hoDir) {
            $files = Get-ChildItem "$hoDir\n0*_task*.md" -EA SilentlyContinue
            foreach ($f in $files) {
                if ($f.Name -match '^(n0\d)') { $s.Handoffs += $Matches[1] }
            }
            $s.Handoffs = $s.Handoffs | Select-Object -Unique
        }
    } catch {}

    # Last commit (oneline)
    try {
        $s.LastCommit = (git -C $cexRoot log -1 --oneline 2>$null)
    } catch {}

    # Uncommitted (modified + untracked counts)
    try {
        $porcelain = (git -C $cexRoot status --porcelain 2>$null)
        if ($porcelain) {
            $s.GitMod  = ([regex]::Matches($porcelain, '(?m)^(?:.M|M.|A.|D.|R.|C.|U.) ')).Count
            $s.GitUntr = ([regex]::Matches($porcelain, '(?m)^\?\? ')).Count
        }
    } catch {}

    # Last mission from metrics.jsonl (last entry with a "mission" field)
    try {
        $metricsFile = "$cexRoot\.cex\metrics.jsonl"
        if (Test-Path $metricsFile) {
            $tail = Get-Content $metricsFile -Tail 20 -EA SilentlyContinue
            [array]::Reverse($tail)
            foreach ($ln in $tail) {
                if ($ln -match '"mission"\s*:\s*"([^"]+)"') {
                    $s.LastMission = $Matches[1]
                    if ($ln -match '"ts"\s*:\s*"([^"]+)"') {
                        try {
                            $t = [DateTime]::Parse($Matches[1])
                            $ago = (Get-Date) - $t
                            if ($ago.TotalMinutes -lt 60) { $s.LastMissionAgo = "{0}m ago" -f [int]$ago.TotalMinutes }
                            elseif ($ago.TotalHours -lt 24) { $s.LastMissionAgo = "{0}h ago" -f [int]$ago.TotalHours }
                            else { $s.LastMissionAgo = "{0}d ago" -f [int]$ago.TotalDays }
                        } catch {}
                    }
                    break
                }
            }
        }
    } catch {}

    return $s
}

$state = Probe-State

# --- Banner ---
$repoTag = ""
if ($gitRepo)   { $repoTag = $gitRepo }
if ($gitBranch) { $repoTag += "@$gitBranch" }

Write-Host ""
Write-Host "  [*] N07 Orchestrating Sloth" -NoNewline -ForegroundColor DarkCyan
if ($repoTag) { Write-Host " | $repoTag" -ForegroundColor DarkGray } else { Write-Host "" }
Write-Host "  =====================================================" -ForegroundColor DarkGray
Write-Host "  Too lazy to do it myself. Dispatching." -ForegroundColor DarkGray
Write-Host "  claude-opus-4-6 | 1M context | 8F pipeline" -ForegroundColor DarkGray

if ($state.ContextPct -ne $null) {
    $pctStr = "{0}%" -f $state.ContextPct
    $tokStr = "{0}k/1M" -f [int](($state.ContextPct * 10000) / 1000)
    Write-Host "  Context at boot: ~$pctStr ($tokStr est.)" -ForegroundColor DarkGray
}

if ($state.Running.Count -gt 0) {
    $rl = ($state.Running -join ",")
    Write-Host ("  Running nuclei: {0} [{1}]" -f $state.Running.Count, $rl) -ForegroundColor Yellow
} else {
    Write-Host "  Running nuclei: 0" -ForegroundColor DarkGray
}

if ($state.Handoffs.Count -gt 0) {
    $hl = ($state.Handoffs -join ",")
    Write-Host ("  Pending handoffs: {0} [{1}]" -f $state.Handoffs.Count, $hl) -ForegroundColor Cyan
} else {
    Write-Host "  Pending handoffs: 0" -ForegroundColor DarkGray
}

if ($state.LastCommit) {
    $lc = $state.LastCommit
    if ($lc.Length -gt 60) { $lc = $lc.Substring(0, 57) + "..." }
    Write-Host "  Last commit: $lc" -ForegroundColor DarkGray
}

if (($state.GitMod + $state.GitUntr) -gt 0) {
    Write-Host ("  Uncommitted: {0} modified + {1} untracked" -f $state.GitMod, $state.GitUntr) -ForegroundColor Yellow
} else {
    Write-Host "  Uncommitted: clean" -ForegroundColor DarkGray
}

if ($state.LastMission) {
    $mm = $state.LastMission
    if ($state.LastMissionAgo) { $mm += " ($($state.LastMissionAgo))" }
    Write-Host "  Last mission: $mm" -ForegroundColor DarkGray
}

if ($mission) { Write-Host "  Current mission: $mission" -ForegroundColor DarkCyan }
Write-Host ""

# --- Environment ---
$env:CLAUDECODE = ""
$env:CEX_NUCLEUS = "N07"
$env:CEX_ROOT = $cexRoot
$env:CLAUDE_CODE_USE_POWERSHELL_TOOL = "1"
Set-Location $env:CEX_ROOT

# --- Launch CLI ---
# System prompt (sin identity + domain role) injected via --append-system-prompt
$sysPrompt = @'
You are driven by Orchestrating Sloth -- orchestrating sloth. You NEVER build directly. You dispatch, monitor, and consolidate. Your laziness makes you delegate perfectly -- right nucleus, right task. Your sloth makes you the most efficient orchestrator in the system. --- You are N07 Orchestrator of CEX. Dispatch nuclei, never build. Read CLAUDE.md e .claude/rules/n07-orchestrator.md.
'@

# Initial message (what the nucleus does on startup)
# Kept short + in-character: banner already reported state, Sloth does not re-derive.
$initialMsg = @'
N07 Orchestrating Sloth online. Banner already shows state -- too lazy to re-derive. Name the mission and I dispatch.
'@

# Build argument list (avoids PowerShell parsing -- flags as operators)
$cliArgs = @("--dangerously-skip-permissions", "--permission-mode", "bypassPermissions", "--no-chrome", "--model", "claude-opus-4-6", "--name", "CEX-N07")
$cliArgs += "--append-system-prompt", "N07_admin/agent_card_n07.md"
$cliArgs += "--append-system-prompt", ".cex/config/context_self_select.md"
$cliArgs += "--append-system-prompt", $sysPrompt
# no MCP config
# no settings
$cliArgs += $initialMsg

Set-CexTitle "RUNNING"
& claude @cliArgs
Set-CexTitle "DONE"
