@echo off
:: CEX N07 -- CEX-N07-ORCHESTRATOR
:: Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml
:: CLI: pi | Model: anthropic/claude-opus-4-6 | Thinking: xhigh

title CEX-N07-ORCHESTRATOR
set CEX_NUCLEUS=N07
set CEX_ROOT=C:\Users\PC\Documents\GitHub\cex
cd /d "%CEX_ROOT%"

pi --model anthropic/claude-opus-4-6 --thinking xhigh --append-system-prompt ".cex/config/context_self_select.md"
