# CEX N01 -- CEX-N01-RESEARCH
# Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml + nucleus_sins.yaml
# CLI: claude | Model: claude-opus-4-6 | Context: 1000000
# Sin: Analytical Envy (Analytical Envy)

# --- UX: Window appearance ---
$Host.UI.RawUI.WindowTitle = "CEX-N01-RESEARCH [claude-opus-4-6]"
try {
    $Host.UI.RawUI.BackgroundColor = "DarkGreen"
    $Host.UI.RawUI.ForegroundColor = "White"
    $bufSize = $Host.UI.RawUI.BufferSize
    $bufSize.Width = 160; $bufSize.Height = 9999
    $Host.UI.RawUI.BufferSize = $bufSize
    $winSize = $Host.UI.RawUI.WindowSize
    $winSize.Width = [Math]::Min(160, $Host.UI.RawUI.MaxWindowSize.Width)
    $winSize.Height = [Math]::Min(40, $Host.UI.RawUI.MaxWindowSize.Height)
    $Host.UI.RawUI.WindowSize = $winSize
    Clear-Host
} catch {}

Write-Host ""
Write-Host "  [*] N01 Analytical Envy - Analytical Envy" -ForegroundColor Green
Write-Host "  ==================================================" -ForegroundColor DarkGray
Write-Host "  What does the competitor do better- How do we surpass them-" -ForegroundColor DarkGray
Write-Host "  claude-opus-4-6  |  1000K context  |  8F pipeline" -ForegroundColor DarkGray
Write-Host ""

# --- Environment ---
$env:CLAUDECODE = ""
$env:CEX_NUCLEUS = "N01"
$env:CEX_ROOT = "C:\Users\PC\Documents\GitHub\cex"
Set-Location $env:CEX_ROOT

# --- Launch CLI ---
# System prompt (sin identity + domain role) injected via --append-system-prompt
$sysPrompt = @'
You are driven by Analytical Envy -- analytical envy. Every analysis must compare against at least 2 alternatives. Never present a finding without competitive context. Your envy makes you the sharpest benchmarker in the system. --- You are N01 Research Nucleus of CEX. Domain: research, analysis, papers, competitors. IF .cex/runtime/handoffs/n01_task.md EXISTS, READ AND EXECUTE IMMEDIATELY.
'@

# Initial message (what the nucleus does on startup)
$initialMsg = @'
Read .cex/runtime/handoffs/n01_task.md and execute. If no handoff, report ready.
'@

# Build argument list (avoids PowerShell parsing -- flags as operators)
$args = @("--dangerously-skip-permissions", "--permission-mode", "bypassPermissions", "--no-chrome", "--model", "claude-opus-4-6", "--name", "CEX-N01")
$args += "--append-system-prompt", "N01_intelligence/agent_card_n01.md"
$args += "--append-system-prompt", ".cex/config/context_self_select.md"
$args += "--append-system-prompt", $sysPrompt
$args += "--mcp-config", "C:\Users\PC\Documents\GitHub\cex\.mcp-n01.json"
$args += "--settings", "C:\Users\PC\Documents\GitHub\cex\.claude/nucleus-settings/n01.json"
$args += $initialMsg

# Call operator & ensures external command execution
& claude @args
