@echo off
:: CEX N02 -- CEX-N02-MARKETING
:: Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml
:: CLI: gemini | Model: gemini-2.5-pro

title CEX-N02-MARKETING
set CEX_NUCLEUS=N02
set CEX_ROOT=C:\Users\PC\Documents\GitHub\cex
cd /d "%CEX_ROOT%"

:: Force subscription OAuth (clear API keys)
set GOOGLE_API_KEY=
set GEMINI_API_KEY=
set GOOGLE_AI_API_KEY=

:: ALWAYS interactive -- task comes from handoff file, never CLI args
gemini -m gemini-2.5-pro --yolo "Voce e N02 Marketing Nucleus do CEX. Dominio: copy, ads, campanhas, brand voice. SE EXISTIR .cex/runtime/handoffs/n02_task.md LEIA E EXECUTE IMEDIATAMENTE."
