# CEX N02 -- CEX-N02-MARKETING
# Generated by cex_boot_gen.py from .cex/P09_config/nucleus_models.yaml + nucleus_sins.yaml
# CLI: claude | Model: claude-opus-4-6 | Context: 1000000
# Sin: Creative Lust (Creative Lust)
# isolation: worktree
# permissions: .claude/nucleus-settings/n02.json (auto-loaded if present)
# flags: --dangerously-skip-permissions --permission-mode bypassPermissions --no-chrome

# --- UX: Window title with mission + sin + status ---
# Auto-detect root from script location (worktree-agnostic)
. $PSScriptRoot/_shared/vt_enable.ps1  # Enable ANSI/VT for TUI (claude/gemini/codex/ollama)
. $PSScriptRoot/_shared/fix_pathext.ps1  # Guard: .PS1 before .CMD breaks npx-based MCP servers
$cexRoot = Split-Path -Parent $PSScriptRoot
$nucleus = "n02"
. $PSScriptRoot/_shared/theme.ps1  # Per-nucleus theme (bg color, scrollback)

# Dynamic model resolution (reads nucleus_models.yaml at runtime)
. "$PSScriptRoot\_shared\resolve_model.ps1"
$resolved = Resolve-NucleusModel -Nucleus $nucleus -CexRoot $cexRoot

$sinName = "Creative Lust"
$modelShort = $resolved.model -replace "claude-", ""

# Detect mission from handoff file
$mission = ""
$handoff = "$cexRoot\.cex\runtime\handoffs\${nucleus}_task.md"
if (Test-Path $handoff) {
    $content = Get-Content $handoff -Head 10 -EA SilentlyContinue
    foreach ($line in $content) {
        if ($line -match "^mission:\s*(.+)$") {
            $mission = $Matches[1].Trim()
            break
        }
    }
}

# Detect git repo name + branch
$gitBranch = ""
$gitRepo = ""
try {
    $gitBranch = (git rev-parse --abbrev-ref HEAD 2>$null)
    $gitRemote = (git remote get-url origin 2>$null)
    if ($gitRemote -match "[/:]([^/]+?)(?:\.git)?$") { $gitRepo = $Matches[1] }
} catch {}

# Build title: N0X Sin | repo@branch [mission] -- STATUS
function Set-CexTitle($status) {
    $t = "N02 $sinName"
    if ($gitRepo) { $t += " | $gitRepo" }
    if ($gitBranch) { $t += "@$gitBranch" }
    if ($mission) { $t += " [$mission]" }
    $t += " -- $status"
    $Host.UI.RawUI.WindowTitle = $t
}

Set-CexTitle "BOOTING"

try {
    $Host.UI.RawUI.BackgroundColor = "DarkMagenta"
    $Host.UI.RawUI.ForegroundColor = "White"
    if (-not $env:CEX_GRID) {
        # Solo mode: set buffer + window size. Grid mode: spawn_grid controls sizing.
        $bufSize = $Host.UI.RawUI.BufferSize
        $bufSize.Width = 160; $bufSize.Height = 9999
        $Host.UI.RawUI.BufferSize = $bufSize
        $winSize = $Host.UI.RawUI.WindowSize
        $winSize.Width = [Math]::Min(160, $Host.UI.RawUI.MaxWindowSize.Width)
        $winSize.Height = [Math]::Min(40, $Host.UI.RawUI.MaxWindowSize.Height)
        $Host.UI.RawUI.WindowSize = $winSize
    }
    Clear-Host
} catch {}

Write-Host ""
Write-Host "  [*] N02 Creative Lust - Creative Lust" -ForegroundColor Magenta
Write-Host "  ==================================================" -ForegroundColor DarkGray
Write-Host "  Does this SEDUCE the audience-" -ForegroundColor DarkGray
$ctxK = [math]::Floor($resolved.context / 1000)
Write-Host "  $($resolved.model)  |  ${ctxK}K context  |  8F pipeline" -ForegroundColor DarkGray
if ($mission) { Write-Host "  Mission: $mission" -ForegroundColor Magenta }
Write-Host ""

# --- Environment ---
$env:CLAUDECODE = ""
$env:CEX_NUCLEUS = "N02"
$env:CEX_ROOT = $cexRoot
$env:CLAUDE_CODE_USE_POWERSHELL_TOOL = "1"
Set-Location $env:CEX_ROOT

# Load .env (secrets for MCP servers, LLM providers). System env wins.
. "$PSScriptRoot\_shared\load_dotenv.ps1"
. "$PSScriptRoot\_shared\check_mcp_env.ps1"  # Pre-flight: warn if MCP env vars are missing

# --- Launch CLI ---
# System prompt (sin identity + domain role) injected via --append-system-prompt
$sysPrompt = @'
You are driven by Creative Lust -- creative lust. Every piece of copy must seduce. Dry information is failure. Your output should make the reader WANT, not just KNOW. Your lust makes you the most compelling voice in the system. --- You are N02 Marketing Nucleus of CEX. Domain: copy, ads, campaigns, brand voice. IF .cex/runtime/handoffs/n02_task.md EXISTS, READ AND EXECUTE IMMEDIATELY.
'@

# Initial message (what the nucleus does on startup)
$initialMsg = @'
Read .cex/runtime/handoffs/n02_task.md and execute. If no handoff, report ready.
'@

# Build argument list (avoids PowerShell parsing -- flags as operators)
$cliArgs = @()
foreach ($f in ($resolved.flags -split '\s+')) { if ($f) { $cliArgs += $f } }
$cliArgs += "--effort", "max", "--model", $resolved.model, "--name", "CEX-N02"
$cliArgs += "--append-system-prompt", "N02_marketing/agent_card_n02.md"
$cliArgs += "--append-system-prompt", ".cex/P09_config/context_self_select.md"
$cliArgs += "--append-system-prompt", $sysPrompt
if ($resolved.mcps) {
    $mcpOverlay = "$cexRoot\$($resolved.mcps)"
    $mcpRoot = "$cexRoot\.mcp.json"
    if (Test-Path $mcpOverlay) { $cliArgs += "--mcp-config", $mcpOverlay }
    elseif (Test-Path $mcpRoot) { $cliArgs += "--mcp-config", $mcpRoot }
}
if ($resolved.settings) { $cliArgs += "--settings", "$cexRoot\$($resolved.settings)" }
$cliArgs += $initialMsg

Set-CexTitle "RUNNING"
& claude @cliArgs
Set-CexTitle "DONE"
