@echo off
:: CEX N02 — CEX-N02-MARKETING
:: Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml
:: CLI: claude | Model: claude-sonnet-4-20250514

title CEX-N02-MARKETING
set CLAUDECODE=
set CEX_NUCLEUS=N02
set CEX_ROOT=C:\Users\PC\Documents\GitHub\cex
cd /d "%CEX_ROOT%"

set MODEL=--model claude-sonnet-4-20250514
set FLAGS=--dangerously-skip-permissions --no-chrome
set MCP=
set SETTINGS=

:: ALWAYS interactive — task comes from handoff file, never CLI args
claude %FLAGS% %MODEL% %MCP% %SETTINGS% "Voce e N02 Marketing Nucleus do CEX. Dominio: copy, ads, campanhas, brand voice. SE EXISTIR .cex/runtime/handoffs/n02_task.md LEIA E EXECUTE IMEDIATAMENTE."
