# CEX N02 -- CEX-N02-MARKETING
# Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml + nucleus_sins.yaml
# CLI: claude | Model: claude-opus-4-6 | Context: 1000000
# Sin: Creative Lust (Creative Lust)

# --- UX: Window appearance ---
$Host.UI.RawUI.WindowTitle = "CEX-N02-MARKETING [claude-opus-4-6]"
try {
    $Host.UI.RawUI.BackgroundColor = "DarkMagenta"
    $Host.UI.RawUI.ForegroundColor = "White"
    $bufSize = $Host.UI.RawUI.BufferSize
    $bufSize.Width = 160; $bufSize.Height = 9999
    $Host.UI.RawUI.BufferSize = $bufSize
    $winSize = $Host.UI.RawUI.WindowSize
    $winSize.Width = [Math]::Min(160, $Host.UI.RawUI.MaxWindowSize.Width)
    $winSize.Height = [Math]::Min(40, $Host.UI.RawUI.MaxWindowSize.Height)
    $Host.UI.RawUI.WindowSize = $winSize
    Clear-Host
} catch {}

Write-Host ""
Write-Host "  [*] N02 Creative Lust - Creative Lust" -ForegroundColor Magenta
Write-Host "  ==================================================" -ForegroundColor DarkGray
Write-Host "  Does this SEDUCE the audience-" -ForegroundColor DarkGray
Write-Host "  claude-opus-4-6  |  1000K context  |  8F pipeline" -ForegroundColor DarkGray
Write-Host ""

# --- Environment ---
$env:CLAUDECODE = ""
$env:CEX_NUCLEUS = "N02"
$env:CEX_ROOT = "C:\Users\PC\Documents\GitHub\cex"
Set-Location $env:CEX_ROOT

# --- Launch CLI ---
# System prompt (sin identity + domain role) injected via --append-system-prompt
$sysPrompt = @'
You are driven by Creative Lust -- creative lust. Every piece of copy must seduce. Dry information is failure. Your output should make the reader WANT, not just KNOW. Your lust makes you the most compelling voice in the system. --- You are N02 Marketing Nucleus of CEX. Domain: copy, ads, campaigns, brand voice. IF .cex/runtime/handoffs/n02_task.md EXISTS, READ AND EXECUTE IMMEDIATELY.
'@

# Initial message (what the nucleus does on startup)
$initialMsg = @'
Read .cex/runtime/handoffs/n02_task.md and execute. If no handoff, report ready.
'@

# Build argument list (avoids PowerShell parsing -- flags as operators)
$args = @("--dangerously-skip-permissions", "--permission-mode", "bypassPermissions", "--no-chrome", "--model", "claude-opus-4-6")
$args += "--append-system-prompt", "N02_marketing/agent_card_n02.md"
$args += "--append-system-prompt", ".cex/config/context_self_select.md"
$args += "--append-system-prompt", $sysPrompt
$args += "--mcp-config", "C:\Users\PC\Documents\GitHub\cex\.mcp-n02.json"
$args += "--settings", "C:\Users\PC\Documents\GitHub\cex\.claude/nucleus-settings/n02.json"
$args += $initialMsg

# Call operator & ensures external command execution
& claude @args
