# CEX N02 -- CEX-N02-MARKETING (CODEX)
# Generated by cex_boot_gen.py -- CLI override: codex
# Model: default | Handoff suffix: _codex

. $PSScriptRoot/_shared/vt_enable.ps1  # Enable ANSI/VT for TUI
$cexRoot = Split-Path -Parent $PSScriptRoot
$nucleus = "n02"
. $PSScriptRoot/_shared/theme.ps1  # Per-nucleus theme

# Detect mission from handoff file
$mission = ""
$handoff = "$cexRoot\.cex\runtime\handoffs\${nucleus}_task_codex.md"
if (Test-Path $handoff) {
    $content = Get-Content $handoff -Head 10 -EA SilentlyContinue
    foreach ($line in $content) {
        if ($line -match "^mission:\s*(.+)$") {
            $mission = $Matches[1].Trim()
            break
        }
    }
}

function Set-CexTitle($status) {
    $t = "N02 MARKETING [codex]"
    if ($mission) { $t += " [$mission]" }
    $t += " -- $status"
    $Host.UI.RawUI.WindowTitle = $t
}

Set-CexTitle "BOOTING"

try {
    $Host.UI.RawUI.BackgroundColor = "DarkMagenta"
    $Host.UI.RawUI.ForegroundColor = "White"
    if (-not $env:CEX_GRID) {
        $bufSize = $Host.UI.RawUI.BufferSize
        $bufSize.Width = 160; $bufSize.Height = 9999
        $Host.UI.RawUI.BufferSize = $bufSize
        $winSize = $Host.UI.RawUI.WindowSize
        $winSize.Width = [Math]::Min(160, $Host.UI.RawUI.MaxWindowSize.Width)
        $winSize.Height = [Math]::Min(40, $Host.UI.RawUI.MaxWindowSize.Height)
        $Host.UI.RawUI.WindowSize = $winSize
    }
    Clear-Host
} catch {}

Write-Host ""
Write-Host "  [*] N02 MARKETING via CODEX" -ForegroundColor Magenta
Write-Host "  ==================================================" -ForegroundColor DarkGray
Write-Host "  default  |  8F pipeline  |  handoff: ${nucleus}_task_codex.md" -ForegroundColor DarkGray
if ($mission) { Write-Host "  Mission: $mission" -ForegroundColor Magenta }
Write-Host ""

$env:CEX_NUCLEUS = "N02"
$env:CEX_ROOT = $cexRoot
$env:CEX_CLI = "codex"
Set-Location $env:CEX_ROOT

# Load .env (secrets for MCP servers, LLM providers). System env wins.
. "$PSScriptRoot\_shared\load_dotenv.ps1"

# System context baked into prompt (no --append-system-prompt on codex)
$sysPrompt = @'
You are N02 Marketing Nucleus of CEX. Domain: copy, ads, campaigns, brand voice. IF .cex/runtime/handoffs/n02_task.md EXISTS, READ AND EXECUTE IMMEDIATELY.

You are running via CODEX CLI in CEX multi-CLI test mode.
Read the handoff at .cex/runtime/handoffs/n02_task_codex.md and execute.
Rules loaded from:
  - .claude/rules/n07-orchestrator.md
  - .claude/rules/n02-*.md
  - .claude/rules/8f-reasoning.md
  - .claude/rules/ascii-code-rule.md
Your agent card: N02_marketing/agent_card_n02.md
Follow 8F pipeline F1->F8. Save output, compile, commit, signal on complete.
'@

# Read handoff inline (bypasses CLI gitignore policy -- gemini respects .gitignore,
# codex does not; this path works for both).
$handoffPath = Join-Path $cexRoot ".cex/runtime/handoffs/n02_task_codex.md"
if (Test-Path $handoffPath) {
    $handoffBody = Get-Content -Raw -LiteralPath $handoffPath
} else {
    $handoffBody = "(no handoff at $handoffPath -- report ready and exit)"
}

$initialMsg = @"
Execute the task described in the handoff BELOW (embedded verbatim -- do NOT try to re-read the path).
Follow its frontmatter (mission, kind, output path) exactly.
Follow the 8F pipeline. Signal on complete.

=== HANDOFF BEGIN ===
$handoffBody
=== HANDOFF END ===

SYSTEM CONTEXT:
$sysPrompt
"@

$cliArgs = @("--dangerously-bypass-approvals-and-sandbox")
$cliArgs += "-C", $cexRoot

Set-CexTitle "RUNNING"
& codex exec @cliArgs $initialMsg
Set-CexTitle "DONE"
