# CEX N02 -- CEX-N02-MARKETING (GEMINI)
# Generated by cex_boot_gen.py -- CLI override: gemini
# Model: gemini-2.5-pro | Handoff suffix: _gemini

$cexRoot = Split-Path -Parent $PSScriptRoot
$nucleus = "n02"

# Detect mission from handoff file
$mission = ""
$handoff = "$cexRoot\.cex\runtime\handoffs\${nucleus}_task_gemini.md"
if (Test-Path $handoff) {
    $content = Get-Content $handoff -Head 10 -EA SilentlyContinue
    foreach ($line in $content) {
        if ($line -match "^mission:\s*(.+)$") {
            $mission = $Matches[1].Trim()
            break
        }
    }
}

function Set-CexTitle($status) {
    $t = "N02 MARKETING [gemini]"
    if ($mission) { $t += " [$mission]" }
    $t += " -- $status"
    $Host.UI.RawUI.WindowTitle = $t
}

Set-CexTitle "BOOTING"

$env:CEX_NUCLEUS = "N02"
$env:CEX_ROOT = $cexRoot
$env:CEX_CLI = "gemini"
Set-Location $env:CEX_ROOT

# System context baked into prompt (no --append-system-prompt on gemini)
$sysPrompt = @'
You are N02 Marketing Nucleus of CEX. Domain: copy, ads, campaigns, brand voice. IF .cex/runtime/handoffs/n02_task.md EXISTS, READ AND EXECUTE IMMEDIATELY.

You are running via GEMINI CLI in CEX multi-CLI test mode.
Read the handoff at .cex/runtime/handoffs/n02_task_gemini.md and execute.
Rules loaded from:
  - .claude/rules/n07-orchestrator.md
  - .claude/rules/n02-*.md
  - .claude/rules/8f-reasoning.md
  - .claude/rules/ascii-code-rule.md
Your agent card: N02_marketing/agent_card_n02.md
Follow 8F pipeline F1->F8. Save output, compile, commit, signal on complete.
'@

$initialMsg = @"
Read .cex/runtime/handoffs/n02_task_gemini.md and execute the SELF_AUDIT mission.
Produce the report at the path specified in the handoff frontmatter.
Follow the 8F pipeline. Signal on complete.

SYSTEM CONTEXT:
$sysPrompt
"@

$cliArgs = @("--yolo", "--model", "gemini-2.5-pro")
$cliArgs += "--include-directories", $cexRoot

Set-CexTitle "RUNNING"
# [CEX_TUI_HYGIENE] UTF-8 + buffer sync + color reset (prevents TUI bleed/mojibake)
try {
    # 1. UTF-8 codepage + encoding (Claude/Codex/Gemini emit unicode box-drawing)
    $null = (chcp 65001 2>$null)
    [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
    [Console]::InputEncoding = [System.Text.Encoding]::UTF8
    $env:PYTHONIOENCODING = "utf-8"
    # 2. Sync BufferSize.Width to WindowSize.Width (no horizontal scroll, no clip)
    $win = $Host.UI.RawUI.WindowSize
    $buf = $Host.UI.RawUI.BufferSize
    if ($buf.Width -ne $win.Width) {
        $buf.Width = $win.Width
        $buf.Height = [Math]::Max($win.Height, 3000)
        $Host.UI.RawUI.BufferSize = $buf
    }
    # 3. Reset colors (prevents DarkGreen/RawUI bleed into child CLI TUI)
    $Host.UI.RawUI.BackgroundColor = "Black"
    $Host.UI.RawUI.ForegroundColor = "Gray"
    [Console]::ResetColor()
    Clear-Host
} catch {}
& gemini @cliArgs $initialMsg
Set-CexTitle "DONE"
