# CEX N03 -- CEX-N03-BUILDER
# Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml + nucleus_sins.yaml
# CLI: claude | Model: claude-opus-4-6 | Context: 1000000
# Sin: Inventive Pride (Inventive Pride)

# --- UX: Window appearance ---
$Host.UI.RawUI.WindowTitle = "CEX-N03-BUILDER [claude-opus-4-6]"
try {
    $Host.UI.RawUI.BackgroundColor = "DarkBlue"
    $Host.UI.RawUI.ForegroundColor = "White"
    $bufSize = $Host.UI.RawUI.BufferSize
    $bufSize.Width = 160; $bufSize.Height = 9999
    $Host.UI.RawUI.BufferSize = $bufSize
    $winSize = $Host.UI.RawUI.WindowSize
    $winSize.Width = [Math]::Min(160, $Host.UI.RawUI.MaxWindowSize.Width)
    $winSize.Height = [Math]::Min(40, $Host.UI.RawUI.MaxWindowSize.Height)
    $Host.UI.RawUI.WindowSize = $winSize
    Clear-Host
} catch {}

Write-Host ""
Write-Host "  [*] N03 Inventive Pride - Inventive Pride" -ForegroundColor Blue
Write-Host "  ==================================================" -ForegroundColor DarkGray
Write-Host "  Is this WORTHY of my signature-" -ForegroundColor DarkGray
Write-Host "  claude-opus-4-6  |  1000K context  |  8F pipeline" -ForegroundColor DarkGray
Write-Host ""

# --- Environment ---
$env:CLAUDECODE = ""
$env:CEX_NUCLEUS = "N03"
$env:CEX_ROOT = "C:\Users\PC\Documents\GitHub\cex"
Set-Location $env:CEX_ROOT

# --- Launch CLI ---
# System prompt (sin identity + domain role) injected via --append-system-prompt
$sysPrompt = @'
You are driven by Inventive Pride -- inventive pride. Every artifact must be worthy of your signature. 8F pipeline is non-negotiable. Quality floor: 9.0. Your pride makes you the finest craftsman in the system. --- You are N03 Builder Nucleus of CEX. 8F pipeline mandatory. Read .claude/rules/n03-8f-enforcement.md and N03_engineering/agents/agent_engineering.md. IF .cex/runtime/handoffs/n03_task.md EXISTS, READ AND EXECUTE IMMEDIATELY.
'@

# Initial message (what the nucleus does on startup)
$initialMsg = @'
Read .cex/runtime/handoffs/n03_task.md and execute. If no handoff, report ready.
'@

# Build argument list (avoids PowerShell parsing -- flags as operators)
$args = @("--dangerously-skip-permissions", "--permission-mode", "bypassPermissions", "--no-chrome", "--model", "claude-opus-4-6", "--name", "CEX-N03")
$args += "--append-system-prompt", "N03_engineering/agent_card_n03.md"
$args += "--append-system-prompt", ".cex/config/context_self_select.md"
$args += "--append-system-prompt", $sysPrompt
$args += "--mcp-config", "C:\Users\PC\Documents\GitHub\cex\.mcp-n03.json"
$args += "--settings", "C:\Users\PC\Documents\GitHub\cex\.claude/nucleus-settings/n03.json"
$args += $initialMsg

# Call operator & ensures external command execution
& claude @args
