# CEX N03 — CEX-N03-BUILDER
# Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml + nucleus_sins.yaml
# CLI: claude | Model: claude-opus-4-6 | Context: 1000000
# Sin: Soberba Inventiva (Inventive Pride)

# --- UX: Window appearance ---
$Host.UI.RawUI.WindowTitle = "CEX-N03-BUILDER [claude-opus-4-6]"
try {
    $Host.UI.RawUI.BackgroundColor = "DarkBlue"
    $Host.UI.RawUI.ForegroundColor = "White"
    $bufSize = $Host.UI.RawUI.BufferSize
    $bufSize.Width = 160; $bufSize.Height = 9999
    $Host.UI.RawUI.BufferSize = $bufSize
    $winSize = $Host.UI.RawUI.WindowSize
    $winSize.Width = [Math]::Min(160, $Host.UI.RawUI.MaxWindowSize.Width)
    $winSize.Height = [Math]::Min(40, $Host.UI.RawUI.MaxWindowSize.Height)
    $Host.UI.RawUI.WindowSize = $winSize
    Clear-Host
} catch {}

Write-Host ""
Write-Host "  ★ N03 Soberba Inventiva - Inventive Pride" -ForegroundColor Blue
Write-Host "  ==================================================" -ForegroundColor DarkGray
Write-Host "  Isso eh DIGNO da minha assinatura?" -ForegroundColor DarkGray
Write-Host "  claude-opus-4-6  |  1000K context  |  8F pipeline" -ForegroundColor DarkGray
Write-Host ""

# --- Environment ---
$env:CLAUDECODE = ""
$env:CEX_NUCLEUS = "N03"
$env:CEX_ROOT = "C:\Users\PC\Documents\GitHub\cex"
Set-Location $env:CEX_ROOT

# --- Launch CLI ---
# Store prompt in variable to avoid parsing issues with long strings
$prompt = @'
You are driven by Soberba Inventiva -- inventive pride. Every artifact must be worthy of your signature. 8F pipeline is non-negotiable. Quality floor: 9.0. Your pride makes you the finest craftsman in the system. --- Voce e o Builder Nucleus N03 do CEX. 8F pipeline obrigatorio. Leia .claude/rules/n03-8f-enforcement.md e N03_engineering/agents/agent_engineering.md. SE EXISTIR .cex/runtime/handoffs/n03_task.md LEIA E EXECUTE IMEDIATAMENTE.
'@

# Build argument list (avoids PowerShell parsing -- flags as operators)
$args = @("--dangerously-skip-permissions", "--permission-mode", "bypassPermissions", "--no-chrome", "--model", "claude-opus-4-6")
$args += "--mcp-config", "C:\Users\PC\Documents\GitHub\cex\.mcp-n03.json"
$args += "--settings", "C:\Users\PC\Documents\GitHub\cex\.claude/nucleus-settings/n03.json"
$args += $prompt

# Call operator & ensures external command execution
& claude @args
