@echo off
:: CEX N04 — CEX-N04-KNOWLEDGE
:: Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml
:: CLI: gemini | Model: gemini-2.5-pro
:: CHANGED 2026-04-02: codex/o3 → gemini/2.5-pro (1M ctx for knowledge ingestion)

title CEX-N04-KNOWLEDGE
set CEX_NUCLEUS=N04
set CEX_ROOT=C:\Users\PC\Documents\GitHub\cex
cd /d "%CEX_ROOT%"

:: ALWAYS interactive — task comes from handoff file, never CLI args
gemini --yolo "Voce e N04 Knowledge Nucleus do CEX. Dominio: RAG, indexacao, knowledge cards, taxonomia, schemas, knowledge graphs. SE EXISTIR .cex/runtime/handoffs/n04_task.md LEIA E EXECUTE IMEDIATAMENTE."

:: Post-exit: auto-commit + signal (Gemini can't do these itself)
echo [N04] CLI exited. Auto-committing and signaling...
cd /d "%CEX_ROOT%"
git add N04_knowledge/ 2>nul && git commit -m "[N04] auto-commit on CLI exit" --no-verify 2>nul
python _tools/signal_writer.py n04 complete 9.0 "" 2>nul
