@echo off
:: CEX N04 -- CEX-N04-KNOWLEDGE
:: Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml
:: CLI: claude | Model: claude-opus-4-6

title CEX-N04-KNOWLEDGE
set CLAUDECODE=
set CEX_NUCLEUS=N04
set CEX_ROOT=C:\Users\PC\Documents\GitHub\cex
cd /d "%CEX_ROOT%"

set MODEL=--model claude-opus-4-6
set FLAGS=--dangerously-skip-permissions --permission-mode bypassPermissions --no-chrome
set MCP=--mcp-config %CEX_ROOT%\.mcp-n04.json
set SETTINGS=--settings %CEX_ROOT%\.claude\nucleus-settings\n04.json

:: ALWAYS interactive -- task comes from handoff file, never CLI args
claude %FLAGS% %MODEL% %MCP% %SETTINGS% "Voce e N04 Knowledge Nucleus do CEX. Dominio: RAG, indexacao, knowledge cards, taxonomia. SE EXISTIR .cex/runtime/handoffs/n04_task.md LEIA E EXECUTE IMEDIATAMENTE."
