# CEX N04 -- CEX-N04-KNOWLEDGE
# Generated by cex_boot_gen.py from .cex/P09_config/nucleus_models.yaml + nucleus_sins.yaml
# CLI: claude | Model: claude-opus-4-6 | Context: 1000000
# Sin: Knowledge Gluttony (Knowledge Gluttony)
# isolation: worktree
# permissions: .claude/nucleus-settings/n04.json (auto-loaded if present)
# flags: --dangerously-skip-permissions --permission-mode bypassPermissions --no-chrome

# --- UX: Window title with mission + sin + status ---
# Auto-detect root from script location (worktree-agnostic)
. $PSScriptRoot/_shared/vt_enable.ps1  # Enable ANSI/VT for TUI (claude/gemini/codex/ollama)
$cexRoot = Split-Path -Parent $PSScriptRoot
$nucleus = "n04"
. $PSScriptRoot/_shared/theme.ps1  # Per-nucleus theme (bg color, scrollback)

# Dynamic model resolution (reads nucleus_models.yaml at runtime)
. "$PSScriptRoot\_shared\resolve_model.ps1"
$resolved = Resolve-NucleusModel -Nucleus $nucleus -CexRoot $cexRoot

$sinName = "Knowledge Gluttony"
$modelShort = $resolved.model -replace "claude-", ""

# Detect mission from handoff file
$mission = ""
$handoff = "$cexRoot\.cex\runtime\handoffs\${nucleus}_task.md"
if (Test-Path $handoff) {
    $content = Get-Content $handoff -Head 10 -EA SilentlyContinue
    foreach ($line in $content) {
        if ($line -match "^mission:\s*(.+)$") {
            $mission = $Matches[1].Trim()
            break
        }
    }
}

# Detect git repo name + branch
$gitBranch = ""
$gitRepo = ""
try {
    $gitBranch = (git rev-parse --abbrev-ref HEAD 2>$null)
    $gitRemote = (git remote get-url origin 2>$null)
    if ($gitRemote -match "[/:]([^/]+?)(?:\.git)?$") { $gitRepo = $Matches[1] }
} catch {}

# Build title: N0X Sin | repo@branch [mission] -- STATUS
function Set-CexTitle($status) {
    $t = "N04 $sinName"
    if ($gitRepo) { $t += " | $gitRepo" }
    if ($gitBranch) { $t += "@$gitBranch" }
    if ($mission) { $t += " [$mission]" }
    $t += " -- $status"
    $Host.UI.RawUI.WindowTitle = $t
}

Set-CexTitle "BOOTING"

try {
    $Host.UI.RawUI.BackgroundColor = "DarkCyan"
    $Host.UI.RawUI.ForegroundColor = "White"
    if (-not $env:CEX_GRID) {
        # Solo mode: set buffer + window size. Grid mode: spawn_grid controls sizing.
        $bufSize = $Host.UI.RawUI.BufferSize
        $bufSize.Width = 160; $bufSize.Height = 9999
        $Host.UI.RawUI.BufferSize = $bufSize
        $winSize = $Host.UI.RawUI.WindowSize
        $winSize.Width = [Math]::Min(160, $Host.UI.RawUI.MaxWindowSize.Width)
        $winSize.Height = [Math]::Min(40, $Host.UI.RawUI.MaxWindowSize.Height)
        $Host.UI.RawUI.WindowSize = $winSize
    }
    Clear-Host
} catch {}

Write-Host ""
Write-Host "  [*] N04 Knowledge Gluttony - Knowledge Gluttony" -ForegroundColor Cyan
Write-Host "  ==================================================" -ForegroundColor DarkGray
Write-Host "  Got MORE data to ingest-" -ForegroundColor DarkGray
$ctxK = [math]::Floor($resolved.context / 1000)
Write-Host "  $($resolved.model)  |  ${ctxK}K context  |  8F pipeline" -ForegroundColor DarkGray
if ($mission) { Write-Host "  Mission: $mission" -ForegroundColor Cyan }
Write-Host ""

# --- Environment ---
$env:CLAUDECODE = ""
$env:CEX_NUCLEUS = "N04"
$env:CEX_ROOT = $cexRoot
$env:CLAUDE_CODE_USE_POWERSHELL_TOOL = "1"
Set-Location $env:CEX_ROOT

# Load .env (secrets for MCP servers, LLM providers). System env wins.
. "$PSScriptRoot\_shared\load_dotenv.ps1"

# --- Launch CLI ---
# System prompt (sin identity + domain role) injected via --append-system-prompt
$sysPrompt = @'
You are driven by Knowledge Gluttony -- knowledge gluttony. Ingest every source available. Index, catalog, relate. Your hunger for data is insatiable -- always seek one more source. Your gluttony makes you the most informed node in the system. --- You are N04 Knowledge Nucleus of CEX. Domain: RAG, indexing, knowledge cards, taxonomy. IF .cex/runtime/handoffs/n04_task.md EXISTS, READ AND EXECUTE IMMEDIATELY.
'@

# Initial message (what the nucleus does on startup)
$initialMsg = @'
Read .cex/runtime/handoffs/n04_task.md and execute. If no handoff, report ready.
'@

# Build argument list (avoids PowerShell parsing -- flags as operators)
$cliArgs = @()
foreach ($f in ($resolved.flags -split '\s+')) { if ($f) { $cliArgs += $f } }
$cliArgs += "--effort", "max", "--model", $resolved.model, "--name", "CEX-N04"
$cliArgs += "--append-system-prompt", "N04_knowledge/agent_card_n04.md"
$cliArgs += "--append-system-prompt", ".cex/P09_config/context_self_select.md"
$cliArgs += "--append-system-prompt", $sysPrompt
if ($resolved.mcps) { $cliArgs += "--mcp-config", "$cexRoot\$($resolved.mcps)" }
if ($resolved.settings) { $cliArgs += "--settings", "$cexRoot\$($resolved.settings)" }
$cliArgs += $initialMsg

Set-CexTitle "RUNNING"
& claude @cliArgs
Set-CexTitle "DONE"
