@echo off
:: CEX N04 — CEX-N04-KNOWLEDGE
:: Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml
:: CLI: codex | Model: o3

title CEX-N04-KNOWLEDGE
set CEX_NUCLEUS=N04
set CEX_ROOT=C:\Users\PC\Documents\GitHub\cex
cd /d "%CEX_ROOT%"

:: ALWAYS interactive — task comes from handoff file, never CLI args
codex -m o3 --full-auto "Voce e N04 Knowledge Nucleus do CEX. Dominio: RAG, indexacao, knowledge cards, taxonomia. SE EXISTIR .cex/runtime/handoffs/n04_task.md LEIA E EXECUTE IMEDIATAMENTE."
