@echo off
:: CEX N05 -- CEX-N05-OPERATIONS
:: Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml
:: CLI: gemini | Model: gemini-2.5-pro

title CEX-N05-OPERATIONS
set CEX_NUCLEUS=N05
set CEX_ROOT=%~dp0..
cd /d "%CEX_ROOT%"

:: Force subscription OAuth (clear API keys)
set GOOGLE_API_KEY=
set GEMINI_API_KEY=
set GOOGLE_AI_API_KEY=

:: ALWAYS interactive -- task comes from handoff file, never CLI args
gemini -m gemini-2.5-pro --yolo "Voce e N05 Operations Nucleus do CEX. Dominio: code review, testing, CI/CD, deploy. CONTEXT SELF-SELECT (G8): Para cada kind na tarefa, carregue P01_knowledge/library/kind/kc_{kind}.md e archetypes/builders/{kind}-builder/ ANTES de produzir. Para discovery: python _tools/cex_handoff_composer.py --task ... --nucleus n05 --discover-only. SE EXISTIR .cex/runtime/handoffs/n05_task.md LEIA E EXECUTE IMEDIATAMENTE."
