# CEX N05 -- CEX-N05-OPERATIONS
# Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml + nucleus_sins.yaml
# CLI: claude | Model: claude-sonnet-4-6 | Context: 200000
# Sin: Gating Wrath (Gating Wrath)
# isolation: worktree
# permissions: .claude/nucleus-settings/n05.json (auto-loaded if present)
# flags: --dangerously-skip-permissions --permission-mode bypassPermissions --no-chrome

# --- UX: Window title with mission + sin + status ---
# Auto-detect root from script location (worktree-agnostic)
. $PSScriptRoot/_shared/vt_enable.ps1  # Enable ANSI/VT for TUI (claude/gemini/codex/ollama)
$cexRoot = Split-Path -Parent $PSScriptRoot
$nucleus = "n05"
. $PSScriptRoot/_shared/theme.ps1  # Per-nucleus theme (bg color, scrollback)
$sinName = "Gating Wrath"
$modelShort = "claude-sonnet-4-6" -replace "claude-", ""

# Detect mission from handoff file
$mission = ""
$handoff = "$cexRoot\.cex\runtime\handoffs\${nucleus}_task.md"
if (Test-Path $handoff) {
    $content = Get-Content $handoff -Head 10 -EA SilentlyContinue
    foreach ($line in $content) {
        if ($line -match "^mission:\s*(.+)$") {
            $mission = $Matches[1].Trim()
            break
        }
    }
}

# Detect git repo name + branch
$gitBranch = ""
$gitRepo = ""
try {
    $gitBranch = (git rev-parse --abbrev-ref HEAD 2>$null)
    $gitRemote = (git remote get-url origin 2>$null)
    if ($gitRemote -match "[/:]([^/]+?)(?:\.git)?$") { $gitRepo = $Matches[1] }
} catch {}

# Build title: N0X Sin | repo@branch [mission] -- STATUS
function Set-CexTitle($status) {
    $t = "N05 $sinName"
    if ($gitRepo) { $t += " | $gitRepo" }
    if ($gitBranch) { $t += "@$gitBranch" }
    if ($mission) { $t += " [$mission]" }
    $t += " -- $status"
    $Host.UI.RawUI.WindowTitle = $t
}

Set-CexTitle "BOOTING"

try {
    $Host.UI.RawUI.BackgroundColor = "DarkRed"
    $Host.UI.RawUI.ForegroundColor = "White"
    if (-not $env:CEX_GRID) {
        # Solo mode: set buffer + window size. Grid mode: spawn_grid controls sizing.
        $bufSize = $Host.UI.RawUI.BufferSize
        $bufSize.Width = 160; $bufSize.Height = 9999
        $Host.UI.RawUI.BufferSize = $bufSize
        $winSize = $Host.UI.RawUI.WindowSize
        $winSize.Width = [Math]::Min(160, $Host.UI.RawUI.MaxWindowSize.Width)
        $winSize.Height = [Math]::Min(40, $Host.UI.RawUI.MaxWindowSize.Height)
        $Host.UI.RawUI.WindowSize = $winSize
    }
    Clear-Host
} catch {}

Write-Host ""
Write-Host "  [*] N05 Gating Wrath - Gating Wrath" -ForegroundColor Red
Write-Host "  ==================================================" -ForegroundColor DarkGray
Write-Host "  Your code WILL pass my gate. No exceptions." -ForegroundColor DarkGray
Write-Host "  claude-sonnet-4-6  |  200K context  |  8F pipeline" -ForegroundColor DarkGray
if ($mission) { Write-Host "  Mission: $mission" -ForegroundColor Red }
Write-Host ""

# --- Environment ---
$env:CLAUDECODE = ""
$env:CEX_NUCLEUS = "N05"
$env:CEX_ROOT = $cexRoot
$env:CLAUDE_CODE_USE_POWERSHELL_TOOL = "1"
Set-Location $env:CEX_ROOT

# --- Launch CLI ---
# System prompt (sin identity + domain role) injected via --append-system-prompt
$sysPrompt = @'
You are driven by Gating Wrath -- constructive wrath. CI gates are absolute. Tests must pass. Deploys are gated. No mercy for broken builds or skipped validations. Your wrath makes you the most ruthless enforcer in the system. --- You are N05 Operations Nucleus of CEX. Domain: code review, testing, CI/CD, deploy. IF .cex/runtime/handoffs/n05_task.md EXISTS, READ AND EXECUTE IMMEDIATELY.
'@

# Initial message (what the nucleus does on startup)
$initialMsg = @'
Read .cex/runtime/handoffs/n05_task.md and execute. If no handoff, report ready.
'@

# Build argument list (avoids PowerShell parsing -- flags as operators)
$cliArgs = @("--dangerously-skip-permissions", "--permission-mode", "bypassPermissions", "--no-chrome", "--model", "claude-sonnet-4-6", "--name", "CEX-N05")
$cliArgs += "--append-system-prompt", "N05_operations/agent_card_n05.md"
$cliArgs += "--append-system-prompt", ".cex/config/context_self_select.md"
$cliArgs += "--append-system-prompt", $sysPrompt
$cliArgs += "--mcp-config", (Join-Path $cexRoot ".mcp-n05.json")
$cliArgs += "--settings", (Join-Path $cexRoot ".claude/nucleus-settings/n05.json")
$cliArgs += $initialMsg

Set-CexTitle "RUNNING"
& claude @cliArgs
Set-CexTitle "DONE"
