@echo off
:: CEX N05 -- CEX-N05-OPERATIONS
:: Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml
:: CLI: claude | Model: claude-opus-4-6

title CEX-N05-OPERATIONS
set CLAUDECODE=
set CEX_NUCLEUS=N05
set CEX_ROOT=C:\Users\PC\Documents\GitHub\cex
cd /d "%CEX_ROOT%"

set MODEL=--model claude-opus-4-6
set FLAGS=--dangerously-skip-permissions --permission-mode bypassPermissions --no-chrome
set MCP=--mcp-config %CEX_ROOT%\.mcp-n05.json
set SETTINGS=--settings %CEX_ROOT%\.claude\nucleus-settings\n05.json

:: ALWAYS interactive -- task comes from handoff file, never CLI args
claude %FLAGS% %MODEL% %MCP% %SETTINGS% "Voce e N05 Operations Nucleus do CEX. Dominio: code review, testing, CI/CD, deploy. SE EXISTIR .cex/runtime/handoffs/n05_task.md LEIA E EXECUTE IMEDIATAMENTE."
