@echo off
:: CEX N05 — CEX-N05-OPERATIONS
:: Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml
:: CLI: codex | Model: o4-mini

title CEX-N05-OPERATIONS
set CEX_NUCLEUS=N05
set CEX_ROOT=C:\Users\PC\Documents\GitHub\cex
cd /d "%CEX_ROOT%"

:: ALWAYS interactive — task comes from handoff file, never CLI args
codex -m o4-mini --full-auto "Voce e N05 Operations Nucleus do CEX. Dominio: code review, testing, CI/CD, deploy. SE EXISTIR .cex/runtime/handoffs/n05_task.md LEIA E EXECUTE IMEDIATAMENTE."
