# CEX N05 — CEX-N05-OPERATIONS
# Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml
# CLI: claude | Model: claude-opus-4-6 | Context: 1000000

# --- UX: Window appearance ---
$Host.UI.RawUI.WindowTitle = "CEX-N05-OPERATIONS [claude-opus-4-6]"
try {
    $Host.UI.RawUI.BackgroundColor = "DarkGray"
    $Host.UI.RawUI.ForegroundColor = "White"
    $bufSize = $Host.UI.RawUI.BufferSize
    $bufSize.Width = 160; $bufSize.Height = 9999
    $Host.UI.RawUI.BufferSize = $bufSize
    $winSize = $Host.UI.RawUI.WindowSize
    $winSize.Width = [Math]::Min(160, $Host.UI.RawUI.MaxWindowSize.Width)
    $winSize.Height = [Math]::Min(40, $Host.UI.RawUI.MaxWindowSize.Height)
    $Host.UI.RawUI.WindowSize = $winSize
    Clear-Host
} catch {}

Write-Host ""
Write-Host "  N05 OPERATIONS  |  claude-opus-4-6  |  1000K context" -ForegroundColor Gray
Write-Host "  ============================================================" -ForegroundColor DarkGray
Write-Host ""

# --- Environment ---
$env:CLAUDECODE = ""
$env:CEX_NUCLEUS = "N05"
$env:CEX_ROOT = "C:\Users\PC\Documents\GitHub\cex"
Set-Location $env:CEX_ROOT

# --- Launch CLI (ALWAYS interactive — task from handoff, never CLI args) ---
claude --dangerously-skip-permissions --permission-mode bypassPermissions --no-chrome --model claude-opus-4-6 --mcp-config "C:\Users\PC\Documents\GitHub\cex\.mcp-n05.json" --settings "C:\Users\PC\Documents\GitHub\cex\.claude/nucleus-settings/n05.json" "Voce e N05 Operations Nucleus do CEX. Dominio: code review, testing, CI/CD, deploy. SE EXISTIR .cex/runtime/handoffs/n05_task.md LEIA E EXECUTE IMEDIATAMENTE."
