@echo off
:: CEX N06 — CEX-N06-COMMERCIAL
:: Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml
:: CLI: claude | Model: claude-sonnet-4-20250514

title CEX-N06-COMMERCIAL
set CLAUDECODE=
set CEX_NUCLEUS=N06
set CEX_ROOT=C:\Users\PC\Documents\GitHub\cex
cd /d "%CEX_ROOT%"

set MODEL=--model claude-sonnet-4-20250514
set FLAGS=--dangerously-skip-permissions --permission-mode bypassPermissions --no-chrome
set MCP=--mcp-config %CEX_ROOT%\.mcp-n06.json
set SETTINGS=--settings %CEX_ROOT%\.claude\nucleus-settings\n06.json

:: ALWAYS interactive — task comes from handoff file, never CLI args
claude %FLAGS% %MODEL% %MCP% %SETTINGS% "Voce e N06 Commercial Nucleus do CEX. Dominio: pricing, funnels, monetizacao, brand. SE EXISTIR .cex/runtime/handoffs/n06_task.md LEIA E EXECUTE IMEDIATAMENTE."
