# CEX N06 -- CEX-N06-COMMERCIAL
# Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml + nucleus_sins.yaml
# CLI: claude | Model: claude-sonnet-4-6 | Context: 200000
# Sin: Strategic Greed (Strategic Greed)

# --- UX: Window title with mission + sin + status ---
# Auto-detect root from script location (worktree-agnostic)
$cexRoot = Split-Path -Parent $PSScriptRoot
$nucleus = "n06"
$sinName = "Strategic Greed"
$modelShort = "claude-sonnet-4-6" -replace "claude-", ""

# Detect mission from handoff file
$mission = ""
$handoff = "$cexRoot\.cex\runtime\handoffs\${nucleus}_task.md"
if (Test-Path $handoff) {
    $content = Get-Content $handoff -Head 10 -EA SilentlyContinue
    foreach ($line in $content) {
        if ($line -match "^mission:\s*(.+)$") {
            $mission = $Matches[1].Trim()
            break
        }
    }
}

# Detect git repo name + branch
$gitBranch = ""
$gitRepo = ""
try {
    $gitBranch = (git rev-parse --abbrev-ref HEAD 2>$null)
    $gitRemote = (git remote get-url origin 2>$null)
    if ($gitRemote -match "[/:]([^/]+?)(?:\.git)?$") { $gitRepo = $Matches[1] }
} catch {}

# Build title: N0X Sin | repo@branch [mission] -- STATUS
function Set-CexTitle($status) {
    $t = "N06 $sinName"
    if ($gitRepo) { $t += " | $gitRepo" }
    if ($gitBranch) { $t += "@$gitBranch" }
    if ($mission) { $t += " [$mission]" }
    $t += " -- $status"
    $Host.UI.RawUI.WindowTitle = $t
}

Set-CexTitle "BOOTING"

# --- Environment ---
$env:CLAUDECODE = ""
$env:CEX_NUCLEUS = "N06"
$env:CEX_ROOT = $cexRoot
$env:CLAUDE_CODE_USE_POWERSHELL_TOOL = "1"
Set-Location $env:CEX_ROOT

# --- Launch CLI ---
# System prompt (sin identity + domain role) injected via --append-system-prompt
$sysPrompt = @'
You are driven by Strategic Greed -- strategic greed. Every output must have ROI context. What does it cost- What does it earn- Optimize pricing, minimize waste, maximize conversion. Your greed makes you the sharpest business mind in the system. --- You are N06 Commercial Nucleus of CEX. Domain: pricing, funnels, monetization, brand. IF .cex/runtime/handoffs/n06_task.md EXISTS, READ AND EXECUTE IMMEDIATELY.
'@

# Initial message (what the nucleus does on startup)
$initialMsg = @'
Read .cex/runtime/handoffs/n06_task.md and execute. If no handoff, report ready.
'@

# Build argument list (avoids PowerShell parsing -- flags as operators)
$cliArgs = @("--dangerously-skip-permissions", "--permission-mode", "bypassPermissions", "--no-chrome", "--model", "claude-sonnet-4-6", "--name", "CEX-N06")
$cliArgs += "--append-system-prompt", "N06_commercial/agent_card_n06.md"
$cliArgs += "--append-system-prompt", ".cex/config/context_self_select.md"
$cliArgs += "--append-system-prompt", $sysPrompt
$args += "--mcp-config", "C:\Users\CEX\Documents\GitHub\cex\.mcp-n06.json"
$args += "--settings", "C:\Users\CEX\Documents\GitHub\cex\.claude/nucleus-settings/n06.json"
$cliArgs += $initialMsg

Set-CexTitle "RUNNING"
# [CEX_TUI_HYGIENE] UTF-8 + buffer sync + color reset (prevents TUI bleed/mojibake)
try {
    # 1. UTF-8 codepage + encoding (Claude/Codex/Gemini emit unicode box-drawing)
    $null = (chcp 65001 2>$null)
    [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
    [Console]::InputEncoding = [System.Text.Encoding]::UTF8
    $env:PYTHONIOENCODING = "utf-8"
    # 2. Sync BufferSize.Width to WindowSize.Width (no horizontal scroll, no clip)
    $win = $Host.UI.RawUI.WindowSize
    $buf = $Host.UI.RawUI.BufferSize
    if ($buf.Width -ne $win.Width) {
        $buf.Width = $win.Width
        $buf.Height = [Math]::Max($win.Height, 3000)
        $Host.UI.RawUI.BufferSize = $buf
    }
    # 3. Reset colors (prevents DarkGreen/RawUI bleed into child CLI TUI)
    $Host.UI.RawUI.BackgroundColor = "Black"
    $Host.UI.RawUI.ForegroundColor = "Gray"
    [Console]::ResetColor()
    Clear-Host
} catch {}
& claude @cliArgs
Set-CexTitle "DONE"
