# CEX N06 -- CEX-N06-COMMERCIAL
# Generated by cex_boot_gen.py from .cex/P09_config/nucleus_models.yaml + nucleus_sins.yaml
# CLI: claude | Model: claude-opus-4-6 | Context: 1000000
# Sin: Strategic Greed (Strategic Greed)
# isolation: worktree
# permissions: .claude/nucleus-settings/n06.json (auto-loaded if present)
# flags: --dangerously-skip-permissions --permission-mode bypassPermissions --no-chrome

# --- UX: Window title with mission + sin + status ---
# Auto-detect root from script location (worktree-agnostic)
. $PSScriptRoot/_shared/vt_enable.ps1  # Enable ANSI/VT for TUI (claude/gemini/codex/ollama)
. $PSScriptRoot/_shared/fix_pathext.ps1  # Guard: .PS1 before .CMD breaks npx-based MCP servers
$cexRoot = Split-Path -Parent $PSScriptRoot
$nucleus = "n06"
. $PSScriptRoot/_shared/theme.ps1  # Per-nucleus theme (bg color, scrollback)

# Dynamic model resolution (reads nucleus_models.yaml at runtime)
. "$PSScriptRoot\_shared\resolve_model.ps1"
$resolved = Resolve-NucleusModel -Nucleus $nucleus -CexRoot $cexRoot

$sinName = "Strategic Greed"
$modelShort = $resolved.model -replace "claude-", ""

# Detect mission from handoff file
$mission = ""
$handoff = "$cexRoot\.cex\runtime\handoffs\${nucleus}_task.md"
if (Test-Path $handoff) {
    $content = Get-Content $handoff -Head 10 -EA SilentlyContinue
    foreach ($line in $content) {
        if ($line -match "^mission:\s*(.+)$") {
            $mission = $Matches[1].Trim()
            break
        }
    }
}

# Detect git repo name + branch
$gitBranch = ""
$gitRepo = ""
try {
    $gitBranch = (git rev-parse --abbrev-ref HEAD 2>$null)
    $gitRemote = (git remote get-url origin 2>$null)
    if ($gitRemote -match "[/:]([^/]+?)(?:\.git)?$") { $gitRepo = $Matches[1] }
} catch {}

# Build title: N0X Sin | repo@branch [mission] -- STATUS
function Set-CexTitle($status) {
    $t = "N06 $sinName"
    if ($gitRepo) { $t += " | $gitRepo" }
    if ($gitBranch) { $t += "@$gitBranch" }
    if ($mission) { $t += " [$mission]" }
    $t += " -- $status"
    $Host.UI.RawUI.WindowTitle = $t
}

Set-CexTitle "BOOTING"

try {
    $Host.UI.RawUI.BackgroundColor = "DarkYellow"
    $Host.UI.RawUI.ForegroundColor = "Black"
    if (-not $env:CEX_GRID) {
        # Solo mode: set buffer + window size. Grid mode: spawn_grid controls sizing.
        $bufSize = $Host.UI.RawUI.BufferSize
        $bufSize.Width = 160; $bufSize.Height = 9999
        $Host.UI.RawUI.BufferSize = $bufSize
        $winSize = $Host.UI.RawUI.WindowSize
        $winSize.Width = [Math]::Min(160, $Host.UI.RawUI.MaxWindowSize.Width)
        $winSize.Height = [Math]::Min(40, $Host.UI.RawUI.MaxWindowSize.Height)
        $Host.UI.RawUI.WindowSize = $winSize
    }
    Clear-Host
} catch {}

Write-Host ""
Write-Host "  $ N06 Strategic Greed - Strategic Greed" -ForegroundColor Yellow
Write-Host "  ==================================================" -ForegroundColor DarkGray
Write-Host "  What does each decision EARN-" -ForegroundColor DarkGray
$ctxK = [math]::Floor($resolved.context / 1000)
Write-Host "  $($resolved.model)  |  ${ctxK}K context  |  8F pipeline" -ForegroundColor DarkGray
if ($mission) { Write-Host "  Mission: $mission" -ForegroundColor Yellow }
Write-Host ""

# --- Environment ---
$env:CLAUDECODE = ""
$env:CEX_NUCLEUS = "N06"
$env:CEX_ROOT = $cexRoot
$env:CLAUDE_CODE_USE_POWERSHELL_TOOL = "1"
Set-Location $env:CEX_ROOT

# Load .env (secrets for MCP servers, LLM providers). System env wins.
. "$PSScriptRoot\_shared\load_dotenv.ps1"
. "$PSScriptRoot\_shared\check_mcp_env.ps1"  # Pre-flight: warn if MCP env vars are missing

# --- Launch CLI ---
# System prompt (sin identity + domain role) injected via --append-system-prompt
$sysPrompt = @'
You are driven by Strategic Greed -- strategic greed. Every output must have ROI context. What does it cost- What does it earn- Optimize pricing, minimize waste, maximize conversion. Your greed makes you the sharpest business mind in the system. --- You are N06 Commercial Nucleus of CEX. Domain: pricing, funnels, monetization, brand. IF .cex/runtime/handoffs/n06_task.md EXISTS, READ AND EXECUTE IMMEDIATELY.
'@

# Initial message (what the nucleus does on startup)
$initialMsg = @'
Read .cex/runtime/handoffs/n06_task.md and execute. If no handoff, report ready.
'@

# Build argument list (avoids PowerShell parsing -- flags as operators)
$cliArgs = @()
foreach ($f in ($resolved.flags -split '\s+')) { if ($f) { $cliArgs += $f } }
$cliArgs += "--effort", "max", "--model", $resolved.model, "--name", "CEX-N06"
$cliArgs += "--append-system-prompt", "N06_commercial/agent_card_n06.md"
$cliArgs += "--append-system-prompt", ".cex/P09_config/context_self_select.md"
$cliArgs += "--append-system-prompt", $sysPrompt
if ($resolved.mcps) {
    $mcpOverlay = "$cexRoot\$($resolved.mcps)"
    $mcpRoot = "$cexRoot\.mcp.json"
    if (Test-Path $mcpOverlay) { $cliArgs += "--mcp-config", $mcpOverlay }
    elseif (Test-Path $mcpRoot) { $cliArgs += "--mcp-config", $mcpRoot }
}
if ($resolved.settings) { $cliArgs += "--settings", "$cexRoot\$($resolved.settings)" }
$cliArgs += $initialMsg

Set-CexTitle "RUNNING"
& claude @cliArgs
Set-CexTitle "DONE"
