@echo off
:: CEX N07 -- CEX-N07-ORCHESTRATOR
:: Generated by cex_boot_gen.py from .cex/config/nucleus_models.yaml
:: CLI: ollama | Model: qwen3:32b

title CEX-N07-ORCHESTRATOR
set CEX_NUCLEUS=N07
set CEX_ROOT=C:\Users\PC\Documents\GitHub\cex
cd /d "%CEX_ROOT%"

:: Local model -- no API keys needed
ollama run qwen3:32b
