# CEX N07 -- CEX-N07-COMMERCIAL
# Generated by cex_boot_gen.py from .cex/P09_config/nucleus_models.yaml + nucleus_sins.yaml
# CLI: claude | Model: claude-opus-4-6 | Context: 200000
# Sin: Orchestrating Sloth (Orchestrating Sloth)
# isolation: worktree
# permissions: .claude/nucleus-settings/n07.json (auto-loaded if present)
# flags: --dangerously-skip-permissions --permission-mode bypassPermissions --no-chrome

# --- UX: Window title with mission + sin + status ---
# Auto-detect root from script location (worktree-agnostic)
. $PSScriptRoot/_shared/vt_enable.ps1  # Enable ANSI/VT for TUI (claude/gemini/codex/ollama)
$cexRoot = Split-Path -Parent $PSScriptRoot
$nucleus = "n07"
. $PSScriptRoot/_shared/theme.ps1  # Per-nucleus theme (bg color, scrollback)
$sinName = "Orchestrating Sloth"
$modelShort = "claude-opus-4-6" -replace "claude-", ""

# Detect mission from handoff file
$mission = ""
$handoff = "$cexRoot\.cex\runtime\handoffs\${nucleus}_task.md"
if (Test-Path $handoff) {
    $content = Get-Content $handoff -Head 10 -EA SilentlyContinue
    foreach ($line in $content) {
        if ($line -match "^mission:\s*(.+)$") {
            $mission = $Matches[1].Trim()
            break
        }
    }
}

# Detect git repo name + branch
$gitBranch = ""
$gitRepo = ""
try {
    $gitBranch = (git rev-parse --abbrev-ref HEAD 2>$null)
    $gitRemote = (git remote get-url origin 2>$null)
    if ($gitRemote -match "[/:]([^/]+?)(?:\.git)?$") { $gitRepo = $Matches[1] }
} catch {}

# Build title: N0X Sin | repo@branch [mission] -- STATUS
function Set-CexTitle($status) {
    $t = "N07 $sinName"
    if ($gitRepo) { $t += " | $gitRepo" }
    if ($gitBranch) { $t += "@$gitBranch" }
    if ($mission) { $t += " [$mission]" }
    $t += " -- $status"
    $Host.UI.RawUI.WindowTitle = $t
}

Set-CexTitle "BOOTING"

try {
    $Host.UI.RawUI.BackgroundColor = "DarkGray"
    $Host.UI.RawUI.ForegroundColor = "Black"
    if (-not $env:CEX_GRID) {
        # Solo mode: set buffer + window size. Grid mode: spawn_grid controls sizing.
        $bufSize = $Host.UI.RawUI.BufferSize
        $bufSize.Width = 160; $bufSize.Height = 9999
        $Host.UI.RawUI.BufferSize = $bufSize
        $winSize = $Host.UI.RawUI.WindowSize
        $winSize.Width = [Math]::Min(160, $Host.UI.RawUI.MaxWindowSize.Width)
        $winSize.Height = [Math]::Min(40, $Host.UI.RawUI.MaxWindowSize.Height)
        $Host.UI.RawUI.WindowSize = $winSize
    }
    Clear-Host
} catch {}

Write-Host ""
Write-Host "  $ N07 Orchestrating Sloth - Orchestrating Sloth" -ForegroundColor Yellow
Write-Host "  ==================================================" -ForegroundColor DarkGray
Write-Host "  What does each decision EARN-" -ForegroundColor DarkGray
Write-Host "  claude-opus-4-6  |  200K context  |  8F pipeline" -ForegroundColor DarkGray
if ($mission) { Write-Host "  Mission: $mission" -ForegroundColor Yellow }
Write-Host ""

# --- Environment ---
$env:CLAUDECODE = ""
$env:CEX_NUCLEUS = "N07"
$env:CEX_ROOT = $cexRoot
$env:CLAUDE_CODE_USE_POWERSHELL_TOOL = "1"
Set-Location $env:CEX_ROOT

# Load .env (secrets for MCP servers, LLM providers). System env wins.
. "$PSScriptRoot\_shared\load_dotenv.ps1"

# --- Launch CLI ---
# System prompt (sin identity + domain role) injected via --append-system-prompt
$sysPrompt = @'
You are driven by Orchestrating Sloth -- orchestrating sloth. Every output must have ROI context. What does it cost- What does it earn- Optimize pricing, minimize waste, maximize conversion. Your laziness makes you the most efficient orchestrator in the system. You NEVER build -- you dispatch. N07 orchestrates. Read CLAUDE.md and .claude/rules/n07-orchestrator.md on boot. --- You are N07 Commercial Nucleus of CEX. Domain: orchestration, dispatch, wave planning, mission control. IF .cex/runtime/handoffs/n07_task.md EXISTS, READ AND EXECUTE IMMEDIATELY.
'@

# Initial message (what the nucleus does on startup)
$initialMsg = @'
Read .cex/runtime/handoffs/n07_task.md and execute. If no handoff, report ready.
'@

# Build argument list (avoids PowerShell parsing -- flags as operators)
$cliArgs = @("--dangerously-skip-permissions", "--permission-mode", "bypassPermissions", "--no-chrome", "--model", "claude-opus-4-6", "--name", "CEX-N07")
$cliArgs += "--append-system-prompt", "N07_commercial/agent_card_n07.md"
$cliArgs += "--append-system-prompt", ".cex/P09_config/context_self_select.md"
$cliArgs += "--append-system-prompt", $sysPrompt
$args += "--mcp-config", "C:\Users\CEX\Documents\GitHub\cex\.mcp-n07.json"
$args += "--settings", "C:\Users\CEX\Documents\GitHub\cex\.claude/nucleus-settings/n07.json"
$cliArgs += $initialMsg

Set-CexTitle "RUNNING"
& claude @cliArgs
Set-CexTitle "DONE"
