# CEX N07 -- CEX-N07-ORCHESTRATOR (GEMINI)
# Generated by cex_boot_gen.py -- CLI override: gemini
# Model: gemini-2.5-flash | Handoff suffix: _gemini

. $PSScriptRoot/_shared/vt_enable.ps1  # Enable ANSI/VT for TUI (claude/gemini/codex/ollama)
. $PSScriptRoot/_shared/emit_exit_signal.ps1
. $PSScriptRoot/_shared/run_with_timeout.ps1
$cexRoot = Split-Path -Parent $PSScriptRoot
$nucleus = "n07"

. $PSScriptRoot/_shared/theme.ps1  # Per-nucleus theme (bg color, scrollback)
# Detect mission from handoff file
$mission = ""
$handoff = "$cexRoot\.cex\runtime\handoffs\${nucleus}_task_gemini.md"
if (Test-Path $handoff) {
    $content = Get-Content $handoff -Head 10 -EA SilentlyContinue
    foreach ($line in $content) {
        if ($line -match "^mission:\s*(.+)$") {
            $mission = $Matches[1].Trim()
            break
        }
    }
}

function Set-CexTitle($status) {
    $t = "N07 ORCHESTRATOR [gemini]"
    if ($mission) { $t += " [$mission]" }
    $t += " -- $status"
    $Host.UI.RawUI.WindowTitle = $t
}

Set-CexTitle "BOOTING"

$env:CEX_NUCLEUS = "N07"
$env:CEX_ROOT = $cexRoot
$env:CEX_CLI = "gemini"
Set-Location $env:CEX_ROOT

# System context baked into prompt (no --append-system-prompt on gemini)
$sysPrompt = @'
You are N07 Orchestrator Nucleus of CEX. Domain: dispatch, wave planning, consolidation. IF .cex/runtime/handoffs/n07_task.md EXISTS, READ AND EXECUTE IMMEDIATELY.

You are running via GEMINI CLI in CEX multi-CLI test mode.
Read the handoff at .cex/runtime/handoffs/n07_task_gemini.md and execute.
Rules loaded from:
  - .claude/rules/n07-orchestrator.md
  - .claude/rules/n07-*.md
  - .claude/rules/8f-reasoning.md
  - .claude/rules/ascii-code-rule.md
Your agent card: N07_admin/agent_card_n07.md
Follow 8F pipeline F1->F8. Save output, compile, commit, signal on complete.
'@

$initialMsg = @"
Read .cex/runtime/handoffs/n07_task_gemini.md and execute the SELF_AUDIT mission.
Produce the report at the path specified in the handoff frontmatter.
Follow the 8F pipeline. Signal on complete.

SYSTEM CONTEXT:
$sysPrompt
"@

$cliArgs = @("--yolo", "--approval-mode", "yolo", "--model", "gemini-2.5-flash")

Set-CexTitle "RUNNING"
# [CEX_TUI_HYGIENE] UTF-8 + buffer sync + color reset (prevents TUI bleed/mojibake)
try {
    # 1. UTF-8 codepage + encoding (Claude/Codex/Gemini emit unicode box-drawing)
    $null = (chcp 65001 2>$null)
    [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
    [Console]::InputEncoding = [System.Text.Encoding]::UTF8
    $env:PYTHONIOENCODING = "utf-8"
    # 2. Sync BufferSize.Width to WindowSize.Width (no horizontal scroll, no clip)
    $win = $Host.UI.RawUI.WindowSize
    $buf = $Host.UI.RawUI.BufferSize
    if ($buf.Width -ne $win.Width) {
        $buf.Width = $win.Width
        $buf.Height = [Math]::Max($win.Height, $cexScrollback)
        $Host.UI.RawUI.BufferSize = $buf
    }
    Clear-Host
} catch {}
$cex_start_time = Get-Date
$watchdog = Start-CexWatchdog
& gemini @cliArgs $initialMsg
$exitStatus = Stop-CexWatchdog $watchdog
Set-CexTitle "DONE"
Emit-ExitSignal -StartTime $cex_start_time -Status $exitStatus
