# boot/_shared/resolve_model.ps1
# Resolves CLI model + flags for a nucleus from nucleus_models.yaml at RUNTIME.
# Never hardcode models in boot scripts -- this file is the single resolver.
#
# Usage (from a boot script):
#     . "$PSScriptRoot\_shared\resolve_model.ps1"
#     $resolved = Resolve-NucleusModel -Nucleus "n03" -CexRoot $cexRoot
#     $resolved.model    # "claude-opus-4-6"
#     $resolved.cli      # "claude"
#     $resolved.context  # 1000000
#     $resolved.flags    # "--dangerously-skip-permissions ..."
#
# Override: N07 can pass CEX_MODEL_OVERRIDE env var to force a specific model:
#     $env:CEX_MODEL_OVERRIDE = "claude-sonnet-4-6"
#     Then Resolve-NucleusModel returns that instead of YAML value.
#
# Why: boot scripts generated by cex_boot_gen.py used to hardcode the model.
# If nucleus_models.yaml changed, boot scripts were stale. This resolver
# reads YAML at boot time so the config is always authoritative.
#
# ASCII-safe (no emoji per .claude/rules/ascii-code-rule.md)

function Resolve-NucleusModel {
    param(
        [Parameter(Mandatory=$true)]
        [string]$Nucleus,
        [Parameter(Mandatory=$true)]
        [string]$CexRoot
    )

    $yamlPath = Join-Path $CexRoot ".cex\config\nucleus_models.yaml"
    if (-not (Test-Path $yamlPath)) {
        Write-Host "  [WARN] nucleus_models.yaml not found at $yamlPath" -ForegroundColor Yellow
        Write-Host "  [WARN] Falling back to claude-opus-4-6" -ForegroundColor Yellow
        return @{
            cli     = "claude"
            model   = "claude-opus-4-6"
            context = 1000000
            flags   = "--dangerously-skip-permissions --permission-mode bypassPermissions"
            mcps    = ""
            settings = ""
        }
    }

    # Check for orchestrator override (N07 can force a model per dispatch)
    if ($env:CEX_MODEL_OVERRIDE) {
        Write-Host "  [i] Model override active: $($env:CEX_MODEL_OVERRIDE)" -ForegroundColor Cyan
        $overrideModel = $env:CEX_MODEL_OVERRIDE
        # Infer CLI from model name
        $overrideCli = "claude"
        if ($overrideModel -match "^gemini") { $overrideCli = "gemini" }
        if ($overrideModel -match "^gpt")    { $overrideCli = "codex" }
        if ($overrideModel -match "^llama|^qwen|^gemma") { $overrideCli = "ollama" }
        return @{
            cli     = $overrideCli
            model   = $overrideModel
            context = 1000000
            flags   = "--dangerously-skip-permissions --permission-mode bypassPermissions"
            mcps    = ""
            settings = ""
        }
    }

    # Parse YAML with native PowerShell regex (no Python dependency).
    # The nucleus_models.yaml structure is flat enough for regex extraction.
    # Previous Python-based parser failed silently in spawned processes
    # where python was not in PATH (2026-04-25 grid failure).
    $yamlContent = Get-Content $yamlPath -Raw -Encoding UTF8

    # Find the nucleus block: starts with "^{nucleus}:" and ends at next "^[a-z]:" or EOF
    $pattern = "(?m)^${Nucleus}:\s*\r?\n((?:[ #].*\r?\n)*)"
    if ($yamlContent -notmatch $pattern) {
        Write-Host "  [WARN] Nucleus '$Nucleus' not found in YAML -- fallback to opus" -ForegroundColor Yellow
        return @{
            cli     = "claude"
            model   = "claude-opus-4-6"
            context = 1000000
            flags   = "--dangerously-skip-permissions --permission-mode bypassPermissions"
            mcps    = ""
            settings = ""
        }
    }
    $block = $Matches[1]

    # Extract fields with simple regex (key: value or key: "value")
    function Get-YamlField($text, $field, $default) {
        if ($text -match "(?m)^\s+${field}:\s+`"([^`"]*)`"") { return $Matches[1] }
        if ($text -match "(?m)^\s+${field}:\s+`'([^`']*)`'") { return $Matches[1] }
        if ($text -match "(?m)^\s+${field}:\s+(\S+)") { return $Matches[1] }
        return $default
    }

    $result = @{
        cli      = Get-YamlField $block "cli" "claude"
        model    = Get-YamlField $block "model" "claude-opus-4-6"
        context  = [int](Get-YamlField $block "context" "1000000")
        flags    = Get-YamlField $block "flags" ""
        mcps     = Get-YamlField $block "mcps" ""
        settings = Get-YamlField $block "settings" ""
    }

    # Safety: if model is still empty after parsing, hardcode fallback
    if (-not $result.model -or $result.model -eq "" -or $result.model -eq '""') {
        Write-Host "  [WARN] Empty model after parse -- fallback to opus" -ForegroundColor Yellow
        $result.model = "claude-opus-4-6"
    }
    if (-not $result.flags -or $result.flags -eq "" -or $result.flags -eq '""') {
        $result.flags = "--dangerously-skip-permissions --permission-mode bypassPermissions"
    }

    return $result
}
