# boot/_shared/resolve_model.ps1
# Resolves CLI model + flags for a nucleus from nucleus_models.yaml at RUNTIME.
# Never hardcode models in boot scripts -- this file is the single resolver.
#
# Usage (from a boot script):
#     . "$PSScriptRoot\_shared\resolve_model.ps1"
#     $resolved = Resolve-NucleusModel -Nucleus "n03" -CexRoot $cexRoot
#     $resolved.model    # "claude-opus-4-6"
#     $resolved.cli      # "claude"
#     $resolved.context  # 1000000
#     $resolved.flags    # "--dangerously-skip-permissions ..."
#
# Override: N07 can pass CEX_MODEL_OVERRIDE env var to force a specific model:
#     $env:CEX_MODEL_OVERRIDE = "claude-sonnet-4-6"
#     Then Resolve-NucleusModel returns that instead of YAML value.
#
# Why: boot scripts generated by cex_boot_gen.py used to hardcode the model.
# If nucleus_models.yaml changed, boot scripts were stale. This resolver
# reads YAML at boot time so the config is always authoritative.
#
# ASCII-safe (no emoji per .claude/rules/ascii-code-rule.md)

function Resolve-NucleusModel {
    param(
        [Parameter(Mandatory=$true)]
        [string]$Nucleus,
        [Parameter(Mandatory=$true)]
        [string]$CexRoot
    )

    $yamlPath = Join-Path $CexRoot ".cex\config\nucleus_models.yaml"
    if (-not (Test-Path $yamlPath)) {
        Write-Host "  [WARN] nucleus_models.yaml not found at $yamlPath" -ForegroundColor Yellow
        Write-Host "  [WARN] Falling back to claude-opus-4-6" -ForegroundColor Yellow
        return @{
            cli     = "claude"
            model   = "claude-opus-4-6"
            context = 1000000
            flags   = "--dangerously-skip-permissions --permission-mode bypassPermissions"
            mcps    = ""
            settings = ""
        }
    }

    # Check for orchestrator override (N07 can force a model per dispatch)
    if ($env:CEX_MODEL_OVERRIDE) {
        Write-Host "  [i] Model override active: $($env:CEX_MODEL_OVERRIDE)" -ForegroundColor Cyan
        $overrideModel = $env:CEX_MODEL_OVERRIDE
        # Infer CLI from model name
        $overrideCli = "claude"
        if ($overrideModel -match "^gemini") { $overrideCli = "gemini" }
        if ($overrideModel -match "^gpt")    { $overrideCli = "codex" }
        if ($overrideModel -match "^llama|^qwen|^gemma") { $overrideCli = "ollama" }
        return @{
            cli     = $overrideCli
            model   = $overrideModel
            context = 1000000
            flags   = "--dangerously-skip-permissions --permission-mode bypassPermissions"
            mcps    = ""
            settings = ""
        }
    }

    # Parse YAML with Python (PowerShell has no native YAML parser)
    # Single python call extracts all fields as JSON
    $pyScript = @"
import yaml, json, sys
try:
    with open(r'$yamlPath', 'r', encoding='utf-8') as f:
        cfg = yaml.safe_load(f)
    nuc = cfg.get('$Nucleus', {})
    print(json.dumps({
        'cli': nuc.get('cli', 'claude'),
        'model': nuc.get('model', 'claude-opus-4-6'),
        'context': nuc.get('context', 1000000),
        'flags': nuc.get('flags', ''),
        'mcps': nuc.get('mcps', ''),
        'settings': nuc.get('settings', '')
    }))
except Exception as e:
    print(json.dumps({'cli':'claude','model':'claude-opus-4-6','context':1000000,'flags':'','mcps':'','settings':'','error':str(e)}))
"@

    $jsonStr = python -c $pyScript 2>$null
    if (-not $jsonStr) {
        Write-Host "  [WARN] Python YAML parse failed -- fallback to opus" -ForegroundColor Yellow
        return @{
            cli     = "claude"
            model   = "claude-opus-4-6"
            context = 1000000
            flags   = "--dangerously-skip-permissions --permission-mode bypassPermissions"
            mcps    = ""
            settings = ""
        }
    }

    $parsed = $jsonStr | ConvertFrom-Json
    if ($parsed.error) {
        Write-Host "  [WARN] YAML parse error: $($parsed.error)" -ForegroundColor Yellow
    }

    return @{
        cli      = $parsed.cli
        model    = $parsed.model
        context  = [int]$parsed.context
        flags    = $parsed.flags
        mcps     = $parsed.mcps
        settings = $parsed.settings
    }
}
