import pathlib

p05 = pathlib.Path('PSPEC_N05_RAILWAY_SUPERINTENDENT.md')
p02 = pathlib.Path('PSPEC_N02_VISUAL_FRONTEND_ENGINEER.md')

# ===== N05 SPEC =====
s = ""
s += "---\n"
s += "id: pspec_n05_railway_superintendent\n"
s += "kind: constraint_spec\n"
s += "pillar: P06\n"
s += "title: PSPEC N05 Railway Backend Superintendent\n"
s += "version: 1.0.0\n"
s += "created: 2026-04-01\n"
s += "author: n07_admin\n"
s += "domain: operations-engineering\n"
s += "quality_target: 9.0\n"
s += "status: SPEC\n"
s += "scope: N05_operations\n"
s += "tags: [pspec, n05, railway, backend, fastapi, postgresql, deploy]\n"
s += "tldr: N05 evolui de DevOps generico para Railway Backend Superintendent hidratada com dados reais.\n"
s += "density_score: 0.96\n"
s += "---\n\n"
s += "# PSPEC N05 -- Railway Backend Superintendent\n\n"
s += "## 1. VISAO\n\n"
s += "N05 deixa de ser nucleo DevOps generico e se torna **Superintendente Railway/Backend**\n"
s += "dono absoluto do ciclo de vida de APIs em producao.\n\n"
s += "> Pergunta-guia: Este deploy eh seguro, observavel e reversivel?\n\n"
s += "### Estado Atual vs Target\n\n"
s += "| Dimensao | ATUAL | TARGET |\n"
s += "|----------|-------|--------|\n"
s += "| Identidade | DevOps generico | Railway Superintendent |\n"
s += "| Modelo | GPT via Codex CLI | Claude Opus via claude CLI |\n"
s += "| Runtime | codex | claude |\n"
s += "| MCPs | nenhum | railway + postgresql |\n"
s += "| Foco | code review, pytest, debug | deploy, API lifecycle, infra Railway |\n"
s += "| KCs | 1 generico | 12 railway-native |\n"
s += "| Output | logs, patches | railway.toml, migrations, health endpoints |\n\n"
s += "---\n\n"

s += "## 2. HIDRATACAO -- SISTEMA REAL EM PRODUCAO\n\n"
s += "Dados extraidos do backend real (codexa-core/api/) para fundamentar o spec.\n\n"

s += "### 2.1 Topologia Railway (4 servicos)\n\n"
s += "| Servico | Repo | Config | Stack |\n"
s += "|---------|------|--------|-------|\n"
s += "| codexa-api | codexa-core/api/ | api/railway.toml | FastAPI+uvicorn+nixpacks |\n"
s += "| codexa-frontend | fresh-start/ | nixpacks.toml | React+Vite+serve |\n"
s += "| mc-dashboard | localhost/mc-dashboard/ | railway.toml | Node |\n"
s += "| gateway | codexa-core/gateway/ | gateway/railway.toml | Python+uvicorn |\n\n"

s += "### 2.2 Backend API Numeros Reais\n\n"
s += "| Metrica | Valor |\n"
s += "|---------|-------|\n"
s += "| Python files | 198 |\n"
s += "| Lines of code (core/) | ~51K |\n"
s += "| API endpoints (unique) | 141 |\n"
s += "| Domain routers | 31 |\n"
s += "| Core modules | 105 files |\n"
s += "| Environment vars | 63 unique |\n"
s += "| Dependencies | 25+ |\n\n"

s += "### 2.3 Middleware Stack Real (8 layers, ordem importa)\n\n"
s += "1. CORS (outermost - wraps ALL responses incl 401/403/500)\n"
s += "2. TenantRateLimitMiddleware (free=60, pro=120, business=300 req/min)\n"
s += "3. APIKeyMiddleware (JWT + API Key hybrid auth)\n"
s += "4. RLSMiddleware (Row-Level Security, X-User-ID)\n"
s += "5. EndpointRateLimitMiddleware (per-endpoint on LLM ops)\n"
s += "6. body_size_limit (5MB default, 10MB streams)\n"
s += "7. catch_all_exceptions (JSON error responses)\n"
s += "8. request_id_and_timing (X-Request-Id + X-Process-Time)\n\n"

s += "### 2.4 Infraestrutura Real\n\n"
s += "| Componente | Tech | Config |\n"
s += "|------------|------|--------|\n"
s += "| Database | PostgreSQL (Railway plugin) | asyncpg pool min=3 max=20 |\n"
s += "| Cache | Redis (Railway plugin) | hiredis, TTL=60s |\n"
s += "| Auth | JWT + API Key hybrid | PyJWT, bcrypt |\n"
s += "| LLM | Multi-LLM Router | Groq/Cerebras/Gemini/Claude/OpenAI/Ollama |\n"
s += "| Sandbox | E2B | code execution + browser |\n"
s += "| Payments | Stripe + MercadoPago PIX | BRL centavos wallet |\n"
s += "| ERP | Bling OAuth2 | background token refresh |\n"
s += "| Marketplace | MercadoLivre OAuth2 | seller API |\n"
s += "| Email | Resend + Jinja2 | transactional |\n"
s += "| WhatsApp | pywa | Meta Business API |\n"
s += "| Execution | 3-tier pipeline | local/cloud/e2b |\n\n"

s += "### 2.5 Health Check Real\n\n"
s += "HealthResponse: status, version, timestamp, uptime_seconds, environment, database{}, cache{}\n"
s += "Endpoints: /health (full) + /pipeline/health (tiers: local/cloud/e2b)\n\n"

s += "### 2.6 Startup Sequence (14 checks)\n\n"
s += "1. asyncpg pool (SSL negotiation: try ssl=False first)\n"
s += "2. Auto-run pending SQL migrations\n"
s += "3. Redis cache init\n"
s += "4. Rate limiter (Redis or in-memory fallback)\n"
s += "5. E2B sandbox check\n"
s += "6. Stripe billing check\n"
s += "7. MercadoPago check\n"
s += "8. MercadoLivre OAuth + sync data\n"
s += "9. Bling ERP OAuth + background refresh\n"
s += "10. ExecutionPipeline health\n"
s += "11. LLM Usage Tracking + LiteLLM\n"
s += "12. Credit system tables\n"
s += "13. Mentor Pro tables\n"
s += "14. Referral system tables\n\n"

s += "### 2.7 Env Vars Criticas (63 total)\n\n"
s += "Obrigatorias: DATABASE_URL, ANTHROPIC_API_KEY, OPENAI_API_KEY, PORT, ENV\n"
s += "Mock-mode: STRIPE_SECRET_KEY, MERCADOPAGO_ACCESS_TOKEN, E2B_API_KEY\n"
s += "Railway auto: PORT, RAILWAY_ENVIRONMENT\n"
s += "Pool tuning: DB_POOL_MIN=3, DB_POOL_MAX=20, DB_COMMAND_TIMEOUT=60\n"
s += "Rate: CODEXA_RATE_LIMIT_ENABLED\n\n"

s += "### 2.8 Credit System (BRL Wallet)\n\n"
s += "pesquisa=75c, anuncio=50c, foto=100c, full=200c, scrape=FREE\n\n"

s += "---\n\n"

s += "## 3. DECOMPOSICAO 8F\n\n"

s += "### F1 CONSTRAIN\n\n"
s += "6 schemas: railway_toml, api_response, env_var, health_check, middleware_stack, startup_sequence\n"
s += "Todos baseados em artefatos reais do codebase.\n\n"

s += "### F2 BECOME\n\n"
s += "role: Railway/Backend Superintendent\n"
s += "model: claude-opus, runtime: claude, mcps: [railway, postgresql]\n"
s += "12 capabilities hidratadas com sistema real (ver secao 2).\n\n"

s += "### F3 INJECT (12 KCs)\n\n"
s += "| # | KC | Acao | Hidratacao |\n"
s += "|---|-----|------|------------|\n"
s += "| 1 | kc_railway_platform_deep | CREATE | 4 servicos reais |\n"
s += "| 2 | kc_railway_cli_patterns | CREATE | railway up/link/rollback |\n"
s += "| 3 | kc_postgresql_railway | CREATE | asyncpg, SSL, migrations |\n"
s += "| 4 | kc_nixpacks_buildpacks | CREATE | nixpacks.toml real |\n"
s += "| 5 | kc_zero_downtime_deploy | CREATE | 14-step startup |\n"
s += "| 6 | kc_api_health_monitoring | CREATE | HealthResponse real |\n"
s += "| 7 | kc_uvicorn_production | CREATE | startCommand, workers |\n"
s += "| 8 | kc_railway_networking | CREATE | CORS regex, origins |\n"
s += "| 9 | kc_middleware_stack | CREATE | 8-layer stack |\n"
s += "| 10 | kc_credit_system_railway | CREATE | BRL wallet |\n"
s += "| 11 | kc_fastapi_patterns | REUSE | existente P01 |\n"
s += "| 12 | kc_deploy_paas | REUSE | existente P01 |\n\n"

s += "### F4 REASON\n\n"
s += "Deploy chain (10 steps baseados em fluxo real):\n"
s += "verify railway.toml > verify env vars > check migrations > railway link > railway up >\n"
s += "await healthcheck 30s > verify /health > verify /pipeline/health > monitor logs > confirm rate-limit\n\n"
s += "Rollback chain (6 steps, 4-service topology):\n"
s += "identify service > railway logs > assess blast radius > railway rollback > verify health > check CORS\n\n"

s += "### F5 CALL\n\n"
s += ".mcp-n05.json: railway MCP + postgres MCP. Fallback: CLI direto.\n\n"

s += "### F6 PRODUCE\n\n"
s += "6 templates: railway.toml, deploy checklist, rollback plan, health endpoint, middleware stack, env contract\n\n"

s += "### F7 GOVERN\n\n"
s += "6 gates: deploy smoke (30s), rollback plan (4 servicos), migration safe, env complete (63 vars), health full, middleware intact\n\n"

s += "### F8 COLLABORATE\n\n"
s += "dispatch, receives_from N03/N07, handoff_to N03, boot/n05.cmd, _seeds/seed_n05.txt\n\n"

s += "---\n\n"

s += "## 4. ARTEFATOS (30 total: 16 CREATE + 14 REWRITE)\n\n"
s += "Wave 1 -- Identidade + Boot: agent, system_prompt, agent_card, boot, mcp, seed (6)\n"
s += "Wave 2 -- Conhecimento: 10 KCs novos + 1 KC rewrite (11)\n"
s += "Wave 3 -- Schemas + Output: 6 schemas + 4 outputs (10)\n"
s += "Wave 4 -- Quality + Orchestration: quality_gate, dispatch, workflow, chec
